### ISSUE TITLE
Keywords field in TypeScript map should be an array 

### ISSUE THREAD

**Issue by pankajanand18** [mattiasw/ExifReader#105]
### Description

`Keywords` in interface Tag for  TypeScraipt definition is  currently marked as `NumberArrayTag` https://github.com/mattiasw/ExifReader/blob/master/exif-reader.d.ts#L218 
whereas it should be `NumberArrayTag[]` 
it causes an issue that TypeScript linter/compiler raises an error when we try to loop over the `Keywords` field for the value. 
Original file : 
![DSC08401-2](https://user-images.githubusercontent.com/4044854/81466111-d47e1f00-9183-11ea-95b5-4b67d23c98bb.jpg)
Tags by `console.log(tags.iptc.Keywords)` which is an array. 

![Screen Shot 2020-05-08 at 11 29 33 PM](https://user-images.githubusercontent.com/4044854/81466124-f8416500-9183-11ea-8c5b-e513e692655e.png)

**How to reproduce**

1.  
2.  
3.  

**What I expected would happen:**

**What really happened:**

**Comment by pankajanand18** [comment]
https://github.com/mattiasw/ExifReader/pull/106

**Comment by mattiasw** [comment]
Merged and released as version 3.11.2. Thanks for contributing!

**Comment by pankajanand18** [comment]
@mattiasw  thanks for the quick response 🙏
