### ISSUE TITLE
Read MPF Tags

### ISSUE THREAD

**Issue by limhenry** [mattiasw/ExifReader#108]
### Description

How can I read Read MPF Tags using this library?

### Use Case
I want to extract the [depth data from a photo](https://drive.google.com/file/d/1vAzRyFKR80T7nZd-hjbryP8MgweyLxLb/view?usp=sharing) (taken on iPhone)

### Extra Info
 - Reading MPF Tags using exiftool: `exiftool -s -G original.jpg`
![Screen Shot 2020-06-03 at 10 41 50 PM](https://user-images.githubusercontent.com/4544770/83657734-6e9e7f00-a5eb-11ea-98cf-97f904fd6f02.png)
 - Extracting Depth Data using exiftool: `exiftool -b -MPImage2 original.jpg > depth.jpg`
![depth](https://user-images.githubusercontent.com/4544770/83658002-d654ca00-a5eb-11ea-9540-9afeb4ff5180.jpg)

**Comment by mattiasw** [comment]
Hi! Right now it's not possible I'm afraid. It would be some work but shouldn't be that complicated to implement. Can't promise a timeframe for it but I will put it on the top of my list.

**Comment by limhenry** [comment]
Thanks!

**Comment by mattiasw** [comment]
Released as 3.13.0. The images can be accessed by the `tags.Images` array (`tags.mpf.Images` if using `expanded: true`). The image data (for example for saving into a new file or making a Blob) is available at `tags.Images[i].image`. For direct use in an `<img>` tag there is also `tags.Images[i].base64`. See `examples/nodejs/exif.js` for a full example.
