### ISSUE TITLE
please dont use postinstall

### ISSUE THREAD

**Issue by thisconnect** [mattiasw/ExifReader#109]
### Description

NPM is getting bigger and more dangerous. It would be great if this lib was installable with `npm install --ignore-scripts`

**Comment by mattiasw** [comment]
Hi! Postinstall is necessary for the optional functionality of a custom bundle (to the best of my knowledge). However, running `npm install --ignore-scripts` should not be a problem. What's the issue you're seeing when running that command?

**Comment by thisconnect** [comment]
No issue, if you want close it, but I believe it will become best practice to not use postinstall unless you have some native code.

What is the purpose of the postinstall  script, some webpack optimization?

**Comment by mattiasw** [comment]
It's not the perfect solution, I agree. I'm not an npm expert but this was the solution I found and seems to be the way others go too, e.g. Husky.

The purpose is building a custom bundle with only the tags and file types one is interested in. It can reduce the resulting file quite a lot. And if no config has been added in package.json the postinstall script won't do anything. More details here: https://github.com/mattiasw/ExifReader#configure-a-custom-build

**Comment by thisconnect** [comment]
yes that Husky wants to execute on installation makes sense.

Now I also get what the postinstall does in exifreader. I'll close this issue. Thanks for the info.

FYI  `bin` is usually used for making a script available in the PATH and on the commandline, i.e. if you would want an exifreader cli api.

See https://docs.npmjs.com/files/package.json#bin

**Comment by mattiasw** [comment]
Thanks for pointing it out anyway. I'm always interested in how people view things regarding this library.

I currently don't have any plans on making it available as CLI, there are far better tools for that. But if there is interest I will of course have a look. Unless you mean that the bin folder is also special, but I didn't see anything about that on that page.

**Comment by thisconnect** [comment]
your of corse free to put the scripts wherever you like, and bin itself doesn't have any meaning only if you specify a bin property in package.json. In that case it is common that the scripts are also located in a dir `bin`. 
i.e.
- https://github.com/typicode/husky (uses bin as husky is a cli command registered in package.json)
- https://github.com/typicode/husky/blob/master/package.json#L6-L7

**Comment by mattiasw** [comment]
I see, then I understand.

**Comment by mattiasw** [comment]
Related: From 4.41.0 there's an `npx exifreader build` command that can create a custom build without relying on `postinstall`, meaning it's now possible to use both `--ignore-scripts` and still having a custom build.
