### ISSUE TITLE
Keywords not found in JPEG when written by Lightroom

### ISSUE THREAD

**Issue by JJLovin** [mattiasw/ExifReader#111]
Issue Description:
ExifReader doesn’t find the keywords in the Keywords tag in the IPTC section of a JPEG file when the keywords are entered with Adobe Lightroom 6.14

To Reproduce:
1.	In Adobe Lightroom 6.14 import a JPEG file
2.	Add keywords in the Lightroom Keyword Tags field
3.	Write the metadata to the file (Metadata | Write Metadata to File)
4.	Select the JPEG file in the ExifReader ECMAScript example (https://mattiasw.github.io/ExifReader/esm/) to see that the Keywords tag isn’t listed.

To see that the keywords are in the JPEG file I used ExifTool (https://exiftool.org/) to display the tags:
ExifTool -s -a -g1 -w jpegfile.jpg

When I add keywords to a JPEG using ExifTool, ExifReader finds and displays the Keywords as expected.

I’m including four files:
ET-Keywords.jpg – JPEG with keywords added using ExifTool
ET-Keywords.txt – list of tags output by ExifTool
LR-Keywords.jpg – JPEG with keywords added using Lightroom 6.14
LR-Keywords.txt – list of tags output by ExifTool

Thanks in advance for considering this issue,
Jim
![ET-Keywords](https://user-images.githubusercontent.com/9847386/85800583-17756100-b6f6-11ea-8350-bea842a1eaf8.jpg)
[ET-Keywords.txt](https://github.com/mattiasw/ExifReader/files/4834070/ET-Keywords.txt)
![LR-Keywords](https://user-images.githubusercontent.com/9847386/85800590-180df780-b6f6-11ea-93d7-77394b3922b5.jpg)
[LR-Keywords.txt](https://github.com/mattiasw/ExifReader/files/4834071/LR-Keywords.txt)

**Comment by mattiasw** [comment]
Nice find! It was actually a bug in the presentation in the examples, not in the library. It's fixed and deployed now. Thanks!
