### ISSUE TITLE
Add documentation on how to get exif data from image tags

### ISSUE THREAD

**Issue by jaykobi** [mattiasw/ExifReader#113]
All documentation and examples are about how to get image data from a fie input. There is no example on how to get exif data from  an `<img src="image.jpg">` tag. At least for me it is not obvious how to do that.

**Comment by mattiasw** [comment]
You are right, there are none and it's certainly not obvious. I will add an example of that when I have the time. In the meantime you can look at this thread where there are some comments about it. The specific one in the link and the following one is the most important ones. Just remember that the server the image is on needs to send the correct CORS headers.

https://github.com/mattiasw/ExifReader/issues/97#issuecomment-615378876

**Comment by Chillstice** [comment]
By using that fetch method, would it load the image twice and use twice as much bandwidth? Did exif.js do that?
I ask because I had a working script using exif.js on jpegs, but I'm switching to webp now to save bandwidth and decrease loading times.

**Comment by mattiasw** [comment]
Yes, I'm doing the same reasoning as you, there would be only one request. Even if the image is present on the page in an img tag or in some other way has already been loaded, it should be cached by the browser and still be transferred only once. I think exif.js used XMLHttpRequest to load the image but that should work the same as fetch in regards to caching.

**Comment by mattiasw** [comment]
In version 3.16.0 the possibility to pass in a URL was added. No need for doing a fetch oneself anymore.
