### ISSUE TITLE
Extended tags type

### ISSUE THREAD

**Issue by dev-delmastro** [mattiasw/ExifReader#114]
Hello! Thanks for your work.

### Description

when calling `ExifReader.load(arrayBuffer, { extended: true })` the response object does not match the expected type on my end.

**Reproduction**

Source repro: https://stackblitz.com/edit/exifreader-extendedtags-repro
Repro demo: https://exifreader-extendedtags-repro.stackblitz.io/

Sample images: https://github.com/ianare/exif-samples/tree/master/jpg/gps

The repro source code has further details.

**TL;DR**
instead of this https://github.com/mattiasw/ExifReader/blob/master/exif-reader.d.ts#L41
I get this
```typescript
interface MyResponse {
    Thumbnail: object;
    exif: object;
    file: object;
    gps?: object;
}
```

Reading https://github.com/mattiasw/ExifReader#gps this seems to be the intended behavior.
The current response object works just fine for my needs, as long as I shut typescript up by asserting it, so it's a very minor issue.

**Comment by mattiasw** [comment]
Thanks for the report. To be honest, the TS file is a bit behind in general since I don't use TS myself and I'm a bit scared of changing it in case I break something. :-) I will try to update it though and make a PR and then maybe you can try it out if you have the time.

**Comment by mattiasw** [comment]
PR: https://github.com/mattiasw/ExifReader/pull/115
