### ISSUE TITLE
Have a function to extract the exif as a buffer?

### ISSUE THREAD

**Issue by geoff-harper** [mattiasw/ExifReader#116]
My use case is that I merely need to get the bytes out of the file and pass them along in a format where they can easily be put back in. This is a bit of a challenge with the current output since it's formatted for use on the client where I really just need the raw data. I tried `loadView` but it seemed to return the same as `load`.

**Comment by mattiasw** [comment]
Hi! True, that is not really possible right now. I can see a couple of things that may make this tricky, but I assume it's doable. Which parts do you need? Only Exif? Do thumbnail, GPS etc. have do be included? I believe they can at least theoretically be spread out. Any other tags, like IPTC? Another thing I come to think of, depending on the actual use, if the byte order would be different between the original file and the new one my guess is it's not usable at all. But the chance for that happening may be quite small, not really sure how common the different byte orders are.

**Comment by geoff-harper** [comment]
If it's possible to just read and extract the entire range of bytes out of the file then at that point then I'd say the lib had served it's purpose well. How those bytes get re-written into a file on the server would be our problem I suppose

**Comment by mattiasw** [comment]
Sorry for the late reply, vacation times. :-) I think this is going to be tricky to get right. The bytes are not in one simple contiguous block, not even if this would be restricted to JPEGs and Exif. Or that is at least not how the different sections are represented in the specification or how they are looked up in the code. To know for sure if one would really have to get each section by it self or if there is a simpler solution to this, one would have to dig deeper than I've done so far (or just know more than I do :-)). I would of course welcome a PR if it doesn't complicate the code too much, but I don't think I will look at this in the near future. Sorry for the negative reply.

**Comment by geoff-harper** [comment]
No problem. Thanks for looking into it, I didn't realize it would be a significant undertaking. I was hoping it was just an early return before parsing it or something
