### ISSUE TITLE
Support for raw files such as NEF?

### ISSUE THREAD

**Issue by speich** [mattiasw/ExifReader#12]
I would be interested in raw support particularly NEF. You probably already know that, but there is Phil Harvey's exiftool (written in pearl) that already can do that. Wouldn't it possible to copy over from there?

**Comment by mattiasw** [comment]
It would probably be possible to port the perl code to JavaScript but it wouldn't be as easy as just copying it I'm afraid. Currently I don't have the time to do it myself but a pull request is always welcome.

**Comment by speich** [comment]
Maybe you could give me some hints which are the relevant lines of code and what's the main program flow/organization.

**Comment by mattiasw** [comment]
I think this is the file that takes care of the Nikon raw format: http://sourceforge.net/p/exiftool/code/ci/master/tree/lib/Image/ExifTool/NikonCapture.pm
