### ISSUE TITLE
Missing fields in interface ExpandedTags

### ISSUE THREAD

**Issue by ethanius** [mattiasw/ExifReader#122]
In exif-reader.d.ts there is this definition:
```
interface ExpandedTags {
    exif?: Tags,
    iptc?: Tags,
    xmp?: XmpTags,
    icc?: IccTags
}
```

I think there are at least two fields missing. `file?` and `gps?`. I can get both of them when specifiing `{ expanded: true }`, but in TS I get an error trying to access them, because they are not in the interface definition.

**Comment by mattiasw** [comment]
Hi! They are there: https://github.com/mattiasw/ExifReader/blob/master/exif-reader.d.ts#L108
But could be that I never made a release after that fix... In that case I will make one later today.

**Comment by ethanius** [comment]
Yes, that seems to be the case. I did install from NPM and I am sure they are not there. But here on Github there are both of them and some more.

**Comment by mattiasw** [comment]
Done! 3.12.1. Thanks for pointing it out. Sorry I missed publishing it before.
