### ISSUE TITLE
EXIF photo Data: important data missing on iPhone 11 images

### ISSUE THREAD

**Issue by isocroft** [mattiasw/ExifReader#124]
### Description

Thanks for this awesome library !!

I need to access the following data using EXIF v2.2.1:

1. **FocalPlaneResolutionUnit**
2. **FocalPlaneYResolution**
3. **FocalPlaneXResolution**
4. **FocalLength**
5. **PixelXDimension**
6. **PixelYDimension**

Because i would like to use it calculate **Field Of View**, **Sensor Width**  and **Sensor Height** from the above EXIF data using the values above.

Now, only 5) and 6) are extracted from my iPhone 11 using the HTML file input with capture attribute (capture="environment"). 1) through to 4) is not extracted.

**Comment by mattiasw** [comment]
Hi! Can you provide an example image that contains these values? They should already be extracted so maybe there's a bug.

**Comment by isocroft** [comment]
Here you go @mattiasw : 

![10AD45B9-4B64-4F02-948E-34837C0CDC64](https://user-images.githubusercontent.com/5495952/93666249-869fee80-fa74-11ea-924b-6124728fce99.jpeg)

![4FD3904F-0798-43ED-B611-3308F757ACED](https://user-images.githubusercontent.com/5495952/93666253-8d2e6600-fa74-11ea-8861-691ebb531cba.jpeg)
![C819E8B8-0262-45EB-9641-A5614AAEBA0D](https://user-images.githubusercontent.com/5495952/93666254-8f90c000-fa74-11ea-9c2c-c33894e8349d.jpeg)

I think it may be a bug. If you could look into it. I would be so grateful

**Comment by mattiasw** [comment]
Sorry for being vague. I meant a photo taken with the device. So that I can run ExifReader on the photo myself to debug.

**Comment by isocroft** [comment]
Here you go @mattiasw 

![4E6877F6-8C85-40E4-9257-1B50E2136690](https://user-images.githubusercontent.com/5495952/93740246-07302d80-fbe2-11ea-9ac4-2198682aa178.jpeg)

**Comment by mattiasw** [comment]
That photo doesn't seem to have any of the Focal* fields. I checked it using exiftool and it can't find them either. Are you sure they are present in the file? For an online version of exiftool I usually use this one: http://exif.regex.info/exif.cgi

**Comment by isocroft** [comment]
@mattiasw I believe uploading it (the photo) here on **GitHub** (on this issue page) might have stripped the photo file of important EXIF data as is the case with *Whatsapp* and *Twitter* photo file uploads. Can i send it to you via email ?

**Comment by isocroft** [comment]
@mattiasw i have sent the photo to you via email. Thanks a lot.

**Comment by isocroft** [comment]
Thanks a lot for spending time on this @mattiasw . I am grateful. I will have to resort to other means to get the values i seek.

**Comment by mattiasw** [comment]
No problem! Hope it works out.
