### ISSUE TITLE
Custom build failing to generate a new bundle.js

### ISSUE THREAD

**Issue by abitofcode** [mattiasw/ExifReader#125]
### Description

Following the instruction in README.md failed to generate a new bundle.js without a change to findDependentConfig.js

```bash
git clone git@github.com:mattiasw/ExifReader.git
cd ExifReader
npm install

# Running
npm run build
# A full bundle is generated as expected dist/exif-reader.js -> 57KB
```

Added the following to package.json;

```bash
  "exifreader": {
    "include": {
      "tiff": true,
      "exif": [
        "DateTime",
        "BitsPerSample",
        "ColorSpace",
        "CreateDate"
      ]
    }
  },
```

```bash
npm rebuild exifreader
# After that the new bundle should be here: node_modules/exifreader/dist/exif-reader.js but isn't
# bundle.js in dist is also not updated
```

```bash
npm run build
# dist/exif-reader.js is still 57KB
```

Changed line in bin/findDependentConfig.js

```javascript
module.exports = getConfigFromParent.bind(null, path.join(__dirname, '..'));
```

to start looking for package.json in the current folder

```javascript
module.exports = getConfigFromParent.bind(null, path.join(__dirname, '.'));
npm run build
# dist/exif-reader.js is now 8KB
```

npm --version 6.14.4
node --version v12.16.3
Running on Mac OS 10.15.7 Catalina

**Comment by abitofcode** [comment]
I’m clearly suffering from sleep deprivation. This is not an issue when the library is installed into a project as intended rather than working directly with the clone. Doh

**Comment by mattiasw** [comment]
:+1: Glad it solved itself. And before I even had the chance to look. :-)
