### ISSUE TITLE
Thumbnail from HEIC/HEIF file

### ISSUE THREAD

**Issue by TomoyukiAota** [mattiasw/ExifReader#128]
Are there any plans for supporting getting thumbnail from HEIC/HEIF files?

The table in README.md says it's not currently supported, and [the demo](https://mattiasw.github.io/ExifReader/global/) works with JPG but HEIC for thumbnail.
I used the IMG_6996.HEIC and IMG_6996.JPG available in [this link](https://gofile.io/d/BcZIFk).

**Comment by mattiasw** [comment]
Hi! Not really I'm afraid. HEIC is a very different format from the TIFF/JPEG ones and would be trickier to implement. As I understand it the thumbnail in a HEIC file isn't even a full image file that can easily be displayed in a web page (like it is in a JPEG or a WebP). Of course, there are other things to do with it than showing it in a web client, but it's probably the most common use case for a thumbnail.

**Comment by mattiasw** [comment]
Thumbnails are supported in HEIC/HEIF (and AVIF) if they are embedded using the standard Exif method. The format I'm writing about above which the provided test image uses is still not supported and I'm afraid I don't see it becoming a priority anytime soon. Therefore I'm closing this for now. If this gets more attention I will reevaluate.
