### ISSUE TITLE
Output changes after modifying Lightroom image with Exiftool

### ISSUE THREAD

**Issue by lbischof** [mattiasw/ExifReader#129]
### Description

I am observing weird behavior: after changing a single tag in an image (from Lightroom) with Exiftool, the ExifReader output changes dramatically.

**How to reproduce**

1.  Check Exif data of Lightroom exported picture
2.  Modify with Exiftool (I think it doesn't matter which tag). I used: `exiftool '-RegionAreaH=0.55270' IMG_6253.jpg`
3.  Check Exif data

**What I expected would happen:**

The output should stay the same, because I did not modify the value of the tag (set the same value as before)

**What really happened:**

The output of ExifReader changed:

Lighroom:
![IMG_6253_working](https://user-images.githubusercontent.com/1837725/96499543-d9282280-124d-11eb-8112-2dfee41e4c39.jpg)
![image](https://user-images.githubusercontent.com/1837725/96499866-46d44e80-124e-11eb-96fc-53bcba60da23.png)

After Exiftool modification:
![IMG_6253_not-working](https://user-images.githubusercontent.com/1837725/96499788-2c01da00-124e-11eb-95ed-9334dab65e46.jpg)
![image](https://user-images.githubusercontent.com/1837725/96499888-4fc52000-124e-11eb-843e-eda8509b99e1.png)

Initially reported at https://github.com/bpatrik/pigallery2/issues/191

**Comment by mattiasw** [comment]
Hi!

I just checked very quickly so this may not be the full picture, but the XML in the file that contains the tags is indeed changed by the exiftool command, and by quite a lot. See attached files. So if I didn't miss anything here I would say it is expected behavior.
[before.txt](https://github.com/mattiasw/ExifReader/files/5404605/before.txt)
[after.txt](https://github.com/mattiasw/ExifReader/files/5404606/after.txt)

**Comment by lbischof** [comment]
Thank you, then I have to figure out why exiftool changes the metadata.

**Comment by mattiasw** [comment]
I found this thread that touches on that subject. Not sure it helps but maybe it can give some clues. https://exiftool.org/forum/index.php?topic=8159.0

**Comment by lbischof** [comment]
As far as I can see Exiftool converts the data to use `rdf:parseType="Resource"` See: https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-parsetype-resource Is there any way to use Exifreader and ignore the underlying structure (because they both represent the same data)?

**Comment by mattiasw** [comment]
I looked into the code some more and I believe you're correct. There is a bug in the handling of lists where these different ways to represent the same date is just never converted. Unfortunately a fix would be a breaking change. For example, the code referenced in the PiGallery2 ticket you linked would definitely break (the `rdf:Description` should not be exposed like that and would be one of the things that would change). This should of course be fixed but it would then have to go into version 4 which I can't say a timeline for.

**Comment by lbischof** [comment]
Ok, thanks for your reply and the awesome work you are doing here! Then I guess I will create a pull request for Pigallery2.

**Comment by mattiasw** [comment]
This is fixed in version 4.0.0. The two files now has the same output. Thanks for reporting!
