### ISSUE TITLE
Example for ExifReader converting from EXIF-JS

### ISSUE THREAD

**Issue by lkoss** [mattiasw/ExifReader#130]
I am using Oracle APEX for application development. I am currently using dropzone 2.4.1 from 
https://github.com/Dani3lSun/apex-plugin-dropzone to load image files. I am using exif-js but need some new tags that are not in that file. In searching I found yours and loaded the javascript file but everything I tried I can't get ExifReader to work. I looked for some sample JS code and tried a couple of things but no luck. Dropzone has an add (load) event that I can run JS and that is what I used with exif-js. Below is the code that I was able to pull the EXIF data and then put it into fields. I shortened it down to just the pull. I can't seem to figure out how to do this in ExifReader. I get undefined, not a constructor, and other errors. I even tried variations of the Issue: Problem using ExifReader #16. I'm sure I'm not doing something or not doing it right but I'm stumped to figure it out. When the file is dropped it is then this.data and I can use it. Any thoughts?

EXIF.getData(this.data, function() {
  var dttm = EXIF.getTag(this, "DateTimeOriginal");
  var yr = dttm.substr(0,4);
  var mon = dttm.substr(5,2);
  var day = dttm.substr(8,2);
  var dt = mon+'/'+day+'/'+yr;
  var tm = dttm.slice(-8);
  var tags = EXIF.getTag(this, "XPKeywords");
  var make = EXIF.getTag(this, "Make");
  var model = EXIF.getTag(this, "Model");
  var dir = getDirection(EXIF.getTag(this, "GPSImgDirection"));
  if (typeof(dir) == 'undefined') {
     dir = ';';
  }
}

Thank you in advance for all assistance.
Lawrence

**Comment by mattiasw** [comment]
Hi! I can have a look tomorrow evening (CET) and try to set up some example code. In the meantime, if you have time you could add an example of what you've tried so far. It might help me figure it out.

**Comment by lkoss** [comment]
One thing I did was follow jgautier2 example on his closed issue. 
var files = event.target.files;
console.log(files);
var exif = new ExifReader();
console.log(exif);
The error I got was Uncaught TypeError: ExifReader is not a constructor

I tried one of your pieces
var files = event.target.files;
const tags = ExifReader.load(files); and also const tags = ExifReader.load(this.data)
The error I got was Uncaught Error: DataView: Passed buffer type is unsupported.

I also tried
var files = this.data;
var reader = new FileReader();
console.log(reader); // I see the reader
reader.onload = function (readerEvent) {
var tags = ExifReader.load(this.data);
  console.log(tags);
} // doesn't get inside the function to load the tags

If I do just the var tags = ExifReader.load(this.data); I get the Passed buffer type error as above.

I've googled to try and find an example with no luck. I am somewhat knowledgeable in javascript but no expert. How do I instantiate an ExifReader in javascript?

I tried looking at your example web page but didn't help. You are loading several other javascript files but I couldn't determine if they were needed. 

Not sure what else to do.

Thank you in advance for all assistance.
Lawrence

**Comment by mattiasw** [comment]
Thanks for the code. I tried to gather what you wrote and combine it into something I think should work in your case. Please try it out and let me know how it goes. (An additonal thing, is this in the browser or on the server? Sounded like it could be both.)

```
const reader = new FileReader();

reader.onload = function (readerEvent) {
    try {
        const tags = ExifReader.load(readerEvent.target.result);
        console.log(tags);
    } catch (error) {
        console.error(error);
    }
};

reader.readAsArrayBuffer(this.data);
```

**Comment by lkoss** [comment]
That worked. This is in the browser. The user drags and drop one of more images then then I process them for the EXIF data. Now I just have to just work out when some of the EXIF data is missing. Some of the photos are from a GPS camera and others are from a Toughbook laptop. The laptop allows adding some tags which will come in handy. The exif-js didn't handle these tags but yours does. 
Thanks for all your help.
Lawrence

**Comment by lkoss** [comment]
I noticed that you are not pulling the filename. It's in the EXIF but I don't see it in any of the parts. Before I was able to pull it from the this.data info but that's not available inside the reader function. Is there a way to catch it?
Thank you in advance for all assistance.
Lawrence

**Comment by lkoss** [comment]
Disregard. Figured out how to capture before the reader event.

Thanks again for all your help. Stay Safe.
Lawrence

**Comment by mattiasw** [comment]
Good to hear!
