### ISSUE TITLE
Crash on some files

### ISSUE THREAD

**Issue by borisgontar** [mattiasw/ExifReader#135]
### Description

ExifReader 3.12.5 crashes on certain files (see attached) when called with {expanded: true}. The exception is: "TypeError: Cannot read property '0' of undefined". Does not happen when called without the expanded option. Does not happen on non-HDR images from the same device. To reproduce just call ExifReader.load(fs.readFileSync(file-name), { expanded: true }).

![P_20201002_145848_vHDR_Auto_HP](https://user-images.githubusercontent.com/5704054/99967957-85d25400-2d66-11eb-97d0-f1a5295dcd2b.jpg)

**Comment by mattiasw** [comment]
Hi! That's not good at all. :-) It looks like that image has a faulty GPS longitude value. That should of course not make the library crash though. A fix has been published as 3.12.6.

**Comment by borisgontar** [comment]
Worked for me. Thanks for quick response.
