### ISSUE TITLE
Multiple files

### ISSUE THREAD

**Issue by feichter** [mattiasw/ExifReader#137]
Hi

Excellent script, thanks!

Is there an easy way to submit multiple files? Maybe with a foreach loop?

Many thanks.

**Comment by feichter** [comment]
Well, this is as far as I have got for now....

Changed <input type="file" id="file" name="file"> to <input type="file" id="fileList" name="fileList" multiple>

Then added this to the head:

$(document).ready(function(){        
   $('#fileList').change('change', function (){
          for (var i = 0; i < this.files.length; i++){
            alert(this.files[i].name);
          }
   });
});

Which of course alerts the file names.

Now, in exif.js, I need to change:

   document.getElementById('file').addEventListener('change', handleFile, false);

to something and add a trigger to the jquery script.

Any ideas?

Many thanks.

**Comment by mattiasw** [comment]
Hi! I would do something like this (not tested):
```
$(document).ready(function () {
    $('#fileList').change('change', function () {
        loadExif(this.files, function (exif) {
            console.log(exif);
        });
    });
});

function loadExif(files, callback) {
    var exif = [];
    $(this.files).each(function (file) {
        var reader = new FileReader();
        reader.onload = function (readerEvent) {
            exif.push(ExifReader.load(readerEvent.target.result));
            if (exif.length === files.length) {
                callback(exif);
            }
        };
        reader.readAsArrayBuffer(file);
    }
}
```

**Comment by feichter** [comment]
Great thanks for that. Will try tomorrow... 



On Mattias Wallander <notifications@github.com>, 29 Nov 2020 19:44 wrote:
Hi! I would do something like this (not tested):
$(document).ready(function () {
    $('#fileList').change('change', function () {
        loadExif(this.files, function (exif) {
            console.log(exif);
        });
    });
});

function loadExif(files, callback) {
    var exif = [];
    $(this.files).each(function (file) {
        var reader = new FileReader();
        reader.onload = function (readerEvent) {
            exif.push(ExifReader.load(readerEvent.target.result));
            if (exif.length === files.length) {
                callback(exif);
            }
        };
        reader.readAsArrayBuffer(file);
    }
}


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mattiasw/ExifReader/issues/137#issuecomment-735444079",
"url": "https://github.com/mattiasw/ExifReader/issues/137#issuecomment-735444079",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by feichter** [comment]
Hi Matthias

Sorry, still no luck. Hope you can help me.
I have used your suggestion (slightly modified):

---------------------------------------------------
    $(document).ready(function(){
	$('#fileList').change('change', function () {
        loadExif(this.files, function (exif) {
            console.log(exif);
            });
        });
    });

    function loadExif(files, callback) {
       var exif = [];
       $(files).each(function(file) {    // CHANGED THIS LINE
	  console.log("file " + files[0].name);
          var reader = new FileReader();
          reader.onload = function (readerEvent) {
              exif.push(ExifReader.load(readerEvent.target.result));
              if (exif.length === files.length) {
                  callback(exif);
              }
          };
	  reader.readAsArrayBuffer(files);  // CHANGED THIS LINE
      });  // CHANGED THIS LINE
    }
-----------------------------------------------------
The console now gives me the name of the first file followed by this error:

    FileReader.readAsArrayBuffer: Argument 1 does not implement interface Blob.

Also, I am linking the scripts like this in the head section:

    <script src="../js/exif/utils.js"></script>
    <script data-main="../js/exif/exif.js" src="../js/exif/require.min.js"></script>

Many thanks for your help.

**Comment by mattiasw** [comment]
`reader.readAsArrayBuffer` needs a single file so that line should be `reader.readAsArrayBuffer(file);` And the `console.log` will currently only print the first file multiple times so that one should be `console.log("file " + file.name);`.

**Comment by feichter** [comment]
Hi

Finally solved my problem. The code below may help someone who is looking to get the exif data from multiple files. The script below only displays the 'DateTime' parameters, however with the console.log you should be able to quickly add more (or all) parameters.

    <script src="../js/exif/exif-reader.js"></script>

     <script language="javascript">
     $(document).ready(function(){
      $(':file').change(function(){
        for(var i=0; i< this.files.length; i++){
	      loadExif(this.files[i]);
	    }
      });
    });

    function loadExif(files){
      var exif = [];
      $(files).each(function(file){
        var reader = new FileReader();
        reader.onload = function (readerEvent){
          exif.push(ExifReader.load(readerEvent.target.result));
	      $.each(exif, function(index, val) {
	        //console.log("FILENAME: " + files.name);
		      $.each(val, function(i, v) {
		        // THIS SHOWS ALL THE EXIF VALUES
    	               //console.log(i + ": "  + v.value);
		        if(i == 'DateTime'){
			      var dateTime = v.value;
			      var parts = dateTime.toString().split(":");
			      var dateTimeMysql = parts[0] + "-" + parts[1] + "-" + parts[2] + ":" + parts[3] + ":" + parts[4];
			      $("#dateTime").append(files.name + ": " + dateTimeMysql + "<br>"); 
		        }
		      });
	      });
        };
	    reader.readAsArrayBuffer(files);
      });
    }
    </script>

HTML:

    <input type="file" id="fileList" name="fileList" multiple>
    <div id="dateTime"></div>

**Comment by mattiasw** [comment]
Great!
