### ISSUE TITLE
IPTC branch fails to read exif on some images

### ISSUE THREAD

**Issue by logistiker** [mattiasw/ExifReader#14]
I've found this code to be problematic on the IPTC branch:

```
      if (dataView.getUint8(this._iptcDataOffset, false) !== 0x1c) {
        throw new Error('Not an IPTC NAA resource tag.');
      }
```
Apparently if it encounters an exif tag it doesn't know how to parse, reading the exif data fails entirely.  Removing this code allows it to read all the exif tags properly for that image and sets the ones it doesn't know about as undefined-56 for example.  I think this a better way to deal with reading the data so that at least some data can be read.

**Comment by mattiasw** [comment]
Fixed by #15.
