### ISSUE TITLE
RatingPercent overwrites Rating

### ISSUE THREAD

**Issue by kagahd** [mattiasw/ExifReader#148]
### Description

For the attached photo, XnView is showing both tags `xmp.Rating:3` and `MicrosoftPhoto.Rating:50` while ExifReader shows only `Rating:50`. 

**How to reproduce**

1.  go to https://mattiasw.github.io/ExifReader/global/
2.  choose the attached photo ![two_ratings](https://user-images.githubusercontent.com/17042479/115977293-ef08fe00-a576-11eb-831c-9858a064dd29.jpg)
3.  look for "Rating" which shows only one of both values (50)

**What I expected would happen:**

In this case I'd expect to see `Rating:3` **and** `RatingPercent:50`.

**What really happened:**

ExifReader showed only `Rating:50`.

**Comment by mattiasw** [comment]
Hi! Since they're both named `Rating` that's expected. But it seems other tools have added a special case for the Microsoft weirdness. I will see if I can do the same.

**Comment by kagahd** [comment]
I suggest to add the property `RatingPercent` to store `MicrosoftPhoto.Rating` which values go from 0 to 100. 
The property `Rating` should remain. It should store values from 0 to 5.

**Comment by mattiasw** [comment]
Fixed and published as version 3.15.0. Thanks for reporting!

**Comment by kagahd** [comment]
Thank you very much!
