### ISSUE TITLE
Reading only GPS from EXIF

### ISSUE THREAD

**Issue by NickSutton** [mattiasw/ExifReader#150]
First of all, fantastic work here, thanks so much!

I have the following code to access a remote image at a specified URL and grab the tags, but I am only interested in the GPS data, if it is present. 

`request.get({uri: mediaUrl, encoding: null},function (error, response, buffer) {`
`					    if (!error && response.statusCode == 200) {`
`							const tags = ExifReader.load(buffer, {expanded: true});`
`							listTags(tags);`
`						}`
`					});`

I have tried the following but unsure which package.json to add to (exifReader, or my nodeJS index package.json file?) Basic question probably but hey, help a guy learn!

`  "exifreader": {
    "include": {
        "exif": [
            "DateTime",
            "GPSLatitude",
            "GPSLatitudeRef",
            "GPSLongitude",
            "GPSLongitudeRef",
            "GPSAltitude",
            "GPSAltitudeRef"
        ]
    }
  },`

Tried appending to both files and rebuilding but listTags() is still dumping all the available data from the image. 
Could you help me out?

**Comment by mattiasw** [comment]
Of course! It should go in _your_ `package.json` file. How does the output look? I'm wondering because the way it works when you add this config to `package.json` is that is removes the code that parses and "understands" the parts that were left out and therefore makes the built package much smaller. But it still needs to go through the tag list in the file and see if there is anything it recognizes (for the `exif` group as you've specified, `iptc` etc. will not be parsed). That means it will still see that there are Exif tags but store them under a tag name looking like `undefined-12345`. So if you see a lot of `undefined-12345` tags with some values that is the correct output. But if you see understandable tag names something is wrong.

**Comment by NickSutton** [comment]
Here's the output, ignore the 'error' it's just how I highlight in my logs:

`03/05/2021 13:17:10 error: "file:Bits Per Sample: 8"
03/05/2021 13:17:10 error: "file:Image Height: 3968px"
03/05/2021 13:17:10 error: "file:Image Width: 2976px"
03/05/2021 13:17:10 error: "file:Color Components: 3"
03/05/2021 13:17:10 error: "file:Subsampling: YCbCr4:2:0 (2 2)"
03/05/2021 13:17:10 error: "exif:ImageWidth: 2976"
03/05/2021 13:17:10 error: "exif:ImageLength: 3968"
03/05/2021 13:17:10 error: "exif:BitsPerSample: 8, 8, 8"
03/05/2021 13:17:10 error: "exif:Make: HUAWEI"
03/05/2021 13:17:10 error: "exif:Model: STF-AL10"
03/05/2021 13:17:10 error: "exif:Orientation: Undefined"
03/05/2021 13:17:10 error: "exif:XResolution: 72"
03/05/2021 13:17:10 error: "exif:YResolution: 72"
03/05/2021 13:17:10 error: "exif:ResolutionUnit: inches"
03/05/2021 13:17:10 error: "exif:Software: STF-AL10 9.1.0.201(C00E100R1P9)"
03/05/2021 13:17:10 error: "exif:DateTime: 2019:11:02 14:59:54"
03/05/2021 13:17:10 error: "exif:YCbCrPositioning: centered"
03/05/2021 13:17:10 error: "exif:Exif IFD Pointer: 286"
03/05/2021 13:17:10 error: "exif:GPS Info IFD Pointer: 8532"
03/05/2021 13:17:10 error: "exif:DeviceSettingDescription: [Raw device settings table data]"
03/05/2021 13:17:10 error: "exif:DocumentName: "
03/05/2021 13:17:10 error: "exif:ExposureTime: 0.02"
03/05/2021 13:17:10 error: "exif:FNumber: 2.2"
03/05/2021 13:17:10 error: "exif:ExposureProgram: Normal program"
03/05/2021 13:17:10 error: "exif:ISOSpeedRatings: 125"
03/05/2021 13:17:10 error: "exif:ExifVersion: 0210"
03/05/2021 13:17:10 error: "exif:DateTimeOriginal: 2019:11:02 14:59:54"
03/05/2021 13:17:10 error: "exif:DateTimeDigitized: 2019:11:02 14:59:54"
03/05/2021 13:17:10 error: "exif:ComponentsConfiguration: "
03/05/2021 13:17:10 error: "exif:CompressedBitsPerPixel: 0.95"
03/05/2021 13:17:10 error: "exif:ShutterSpeedValue: 29.8973"
03/05/2021 13:17:10 error: "exif:ApertureValue: 2.27"
03/05/2021 13:17:10 error: "exif:BrightnessValue: 0"
03/05/2021 13:17:10 error: "exif:ExposureBiasValue: 0"
03/05/2021 13:17:10 error: "exif:MaxApertureValue: 2.27"
03/05/2021 13:17:10 error: "exif:MeteringMode: Pattern"
03/05/2021 13:17:10 error: "exif:LightSource: Daylight"
03/05/2021 13:17:10 error: "exif:Flash: Flash did not fire"
03/05/2021 13:17:10 error: "exif:FocalLength: 3.95"
03/05/2021 13:17:10 error: "exif:MakerNote: [Raw maker note data]"
03/05/2021 13:17:10 error: "exif:SubSecTime: 862038"
03/05/2021 13:17:10 error: "exif:SubSecTimeOriginal: 862038"
03/05/2021 13:17:10 error: "exif:SubSecTimeDigitized: 862038"
03/05/2021 13:17:10 error: "exif:FlashpixVersion: 0100"
03/05/2021 13:17:10 error: "exif:ColorSpace: sRGB"
03/05/2021 13:17:10 error: "exif:PixelXDimension: 2976"
03/05/2021 13:17:10 error: "exif:PixelYDimension: 3968"
03/05/2021 13:17:10 error: "exif:Interoperability IFD Pointer: 8502"
03/05/2021 13:17:10 error: "exif:SensingMethod: One-chip color area sensor"
03/05/2021 13:17:10 error: "exif:FileSource: DSC"
03/05/2021 13:17:10 error: "exif:SceneType: A directly photographed image"
03/05/2021 13:17:10 error: "exif:CustomRendered: Custom process"
03/05/2021 13:17:10 error: "exif:ExposureMode: Auto exposure"
03/05/2021 13:17:10 error: "exif:WhiteBalance: Auto white balance"
03/05/2021 13:17:10 error: "exif:DigitalZoomRatio: 1"
03/05/2021 13:17:10 error: "exif:FocalLengthIn35mmFilm: 27"
03/05/2021 13:17:10 error: "exif:SceneCaptureType: Standard"
03/05/2021 13:17:10 error: "exif:GainControl: None"
03/05/2021 13:17:10 error: "exif:Contrast: Normal"
03/05/2021 13:17:10 error: "exif:Saturation: Normal"
03/05/2021 13:17:10 error: "exif:Sharpness: Normal"
03/05/2021 13:17:10 error: "exif:SubjectDistanceRange: Unknown"
03/05/2021 13:17:10 error: "exif:GPSVersionID: Version 2.2"
03/05/2021 13:17:10 error: "exif:GPSLatitudeRef: North latitude"
03/05/2021 13:17:10 error: "exif:GPSLatitude: 38.90384292583333"
03/05/2021 13:17:10 error: "exif:GPSLongitudeRef: East longitude"
03/05/2021 13:17:10 error: "exif:GPSLongitude: 115.46178436277778"
03/05/2021 13:17:10 error: "exif:GPSAltitudeRef: Sea level reference (negative value)"
03/05/2021 13:17:10 error: "exif:GPSAltitude: 0 m"
03/05/2021 13:17:10 error: "exif:GPSTimeStamp: 06:59:54"
03/05/2021 13:17:10 error: "exif:GPSProcessingMethod: Undefined"
03/05/2021 13:17:10 error: "exif:GPSDateStamp: 2019:11:02"
03/05/2021 13:17:10 error: "exif:InteroperabilityIndex: R98"
03/05/2021 13:17:10 error: "exif:InteroperabilityVersion: 0100"`

**Comment by NickSutton** [comment]
Tried again with the code my package.json and rebuilt the package, but the script still produces the above.
Is there anything else I need to do after a rebuild?

**Comment by mattiasw** [comment]
No, that should be it. How are you importing the library?

**Comment by NickSutton** [comment]
`const ExifReader = require('exifreader');`

**Comment by mattiasw** [comment]
Also correct (it won't use the custom build when importing the `src/exif-reader.js` file directly). A couple of questions:

- Did you run `npm rebuild exifreader` from your project's root folder?
- What is the size of this file after the rebuild? `node_modules/exifreader/dist/exif-reader.js`
- Does it make any difference if you add `"jpeg": true` in the `include` block?
- What system are you using (Windows, Linux, MacOS, ...)?
- Is this a public project that I could try for myself?

**Comment by NickSutton** [comment]
Thanks for getting back to me. Here's the answers to your questions:

- Yep
- Filesize is 55734
- See second results
- Linux
- No, I'm afraid it isn't 

With 'jpeg: true', file size is the same and still dumping all the values

**Comment by mattiasw** [comment]
That is the original filesize so something is wrong with the rebuilding. And you are correct, there should be a gps group. Just to be sure, could you double check that you're using one of the newer versions of ExifReader? It's getting late here so closing down for the day. I will continue thinking about this and see if I can come up with anything else.

**Comment by NickSutton** [comment]
Surething, I get version 2.13.1

If the build itself isn't optimised it's not the end of the world. But could you let me know how to print the output of the GPS tags? .value and .description both throw errors when used with your examples.

function listTags(tags) {
    for (const group in tags) {
        for (const name in tags[group]) {
            if (group === 'gps') {
                logger.error(`${group}:${name}: ${tags[group][name]}`);
            } else if ((group === 'Thumbnail') && (name === 'type')) {
                logger.error(`${group}:${name}: ${tags[group][name]}`);
            } else if ((group === 'Thumbnail') && (name === 'image')) {
                logger.error(`${group}:${name}: <image>`);
            } else if ((group === 'Thumbnail') && (name === 'base64')) {
                logger.error(`${group}:${name}: <base64 encoded image>`);
            } else if ((group === 'mpf') && (name === 'Images')) {
                logger.error(`${group}:${name}: ${getMpfImagesDescription(tags[group][name])}`);
            } else if (Array.isArray(tags[group][name])) {
               logger.error(`${group}:${name}: ${tags[group][name].map((item) => item.description).join(', ')}`);
            } else {
               logger.error(`${group}:${name}: ${tags[group][name].description}`);
            }
        }
    }
}`

**Comment by mattiasw** [comment]
That's the issue then, the version is too old. Custom build for tags was introduced in 3.8.0 and the gps group came in 3.11.0.

**Comment by NickSutton** [comment]
Yep, that sorted it.
If I print the GPS group now, I'm only getting lat,lon and altitude. is there was a way to get the reference values too?

'''
request.get({uri: req.body.MediaUrl0, encoding: null},function (error, response, buffer) {
					    if (!error && response.statusCode == 200) {
							const tags = ExifReader.load(buffer, {expanded: true});
						        for (const name in tags['gps']) {
						            logger.info(`${'gps'}:${name}: ${tags['gps'][name]}`);
						        }
						}
					});
'''

**Comment by mattiasw** [comment]
Nice!
If you want the reference values the gps group is not for you. :-) The purpose of it is to translate the gps values into a more human-readable form without having to care about reference. If you need reference just use `GPSLatitudeRef`, `GPSLongitudeRef`, and `GPSAltitudeRef` in the exif group.

**Comment by NickSutton** [comment]
Thanks, have changed approach and no longer using request to get an image from a link, but an uploaded image instead.

Could you let me know where I'm wide of the mark here:

````

	app.post('/upload', upload.single('upload'), (req, res) => {
	
	//	var buf = req.file.buffer.toString('base64');
	//  var buf = req.file.buffer;
	
		const tags = ExifReader.load(req.file.buffer, {expanded: true});
				if(tags){
					if (tags['gps']) {
						
						var mmsGPS = {
							mmsLat: tags['gps']['Latitude'],
							mmsLon: tags['gps']['Longitude'],
							mmsAlt: tags['gps']['Altitude'],
							mmsLatRef: tags['exif']['GPSLatitudeRef'],
							mmsLonRef: tags['exif']['GPSLongitudeRef'],
							mmsAltRef: tags['exif']['GPSAltitudeRef']
						}
						
						logger.info(mmsGPS);
						return mmsGPS;
					}else {
						logger.warn('No GPS information contained in this image.')
					}
				}else {
					logger.warn('No GPS information contained in this image.')
				}
	
		res.send()
		
		
	});

````

I got a `Passed buffer type is unsupported` error message

**Comment by mattiasw** [comment]
I don't know much about this setup but my guess is that `req.file` is not the real file, just a reference to it, so you have to read it first. Maybe something like this:

```
fs.readFile(req.file.path, function (error, data) {
    const tags = ExifReader.load(data, {expanded: true});
}
```

**Comment by NickSutton** [comment]
Hi,

`req.file` was ok, I got this working so far accepting form-data uploads from Postman.
Thanks for all your help, hopefully my random pieces of code may help someone else on a similar journey
````
app.post('/v1/imgUpload', upload.single('upload'), (req, res) => {
		
		const tags = ExifReader.load(req.file.buffer, {expanded: true});
		var uploadStr = { status: 'error', msg: 'No GPS information contained in this image.' };
		
				if(tags){
					if (tags['gps']) {
						
						uploadStr = {
							status: 'OK',
							mmsLat: tags['gps']['Latitude'],
							mmsLon: tags['gps']['Longitude'],
							mmsAlt: tags['gps']['Altitude'],
							mmsLatRef: tags['exif']['GPSLatitudeRef'],
							mmsLonRef: tags['exif']['GPSLongitudeRef'],
							mmsAltRef: tags['exif']['GPSAltitudeRef']
						}
						
						logger.warn('GPS data extracted from an uploaded image!');
						
					}else {
						logger.warn('An image was uploaded but no GPS data could be extracted!');
					}
				}else {
					logger.warn('An image was uploaded but no meta data was available!');
				}

		res.status(200).send(uploadStr);
````
