### ISSUE TITLE
How to run ExifReader on images from webcam

### ISSUE THREAD

**Issue by sahil-syze** [mattiasw/ExifReader#157]
This is a great library for extracting metadata from images. And now we're trying to get focal length metadata from webcam images. Is there a straightforward way to implement that?

Thanks

**Comment by sahil-syze** [comment]
When I run the following code on https://mattiasw.github.io/ExifReader/global/

```
const stream = await navigator.mediaDevices.getUserMedia({ video : true });
const track = stream.getVideoTracks()[0];
let imageCapture = new ImageCapture(track);
imageCapture.takePhoto().then((blob) => {
  const newFile = new File([blob], "MyJPEG.jpg", { type: "image/jpeg" });
  const tags = ExifReader.load(newFile)
  console.log(tags)
})
```
I get the following error message
```
dataview.js:4 Uncaught (in promise) Error: DataView: Passed buffer type is unsupported.
    at new e (dataview.js:4)
    at Lt (exif-reader.js:54)
    at Module.xt (exif-reader.js:39)
    at <anonymous>:4:25
e @ dataview.js:4
Lt @ exif-reader.js:54
xt @ exif-reader.js:39
(anonymous) @ VM46:4
Promise.then (async)
(anonymous) @ VM46:1
```

**Comment by mattiasw** [comment]
Hi! Yeah, the load function doesn't take a File object just yet. I'm working on it though, so if you can wait until the weekend I will push an update. If not, it's still supported, just needs a little bit more code, so have a look at one of the examples: https://mattiasw.github.io/ExifReader/esm/

With your code it should look something like this (not tested):
```
const stream = await navigator.mediaDevices.getUserMedia({ video : true });
const track = stream.getVideoTracks()[0];
let imageCapture = new ImageCapture(track);
imageCapture.takePhoto().then((blob) => {
  const newFile = new File([blob], "MyJPEG.jpg", { type: "image/jpeg" });
  const reader = new FileReader();
  reader.onload = function (readerEvent) {
    const tags = ExifReader.load(readerEvent.target.result);
    console.log(tags)
  };
  reader.readAsArrayBuffer(newFile);
})
```

**Comment by sahil-syze** [comment]
Thank you for your reply. This does seem to work but it is only returning 5 exif tags, namely,

- Bits Per Sample
- Color Components
- Image Height
- Image Width
- Subsampling

Mainly it is missing the one which I require, i.e., `FocalLength`

**Comment by mattiasw** [comment]
Then that's probably because the camera or browser does not record `FocalLength` in the image. And in that case there isn't much to do unfortunately. To double check you could save that image somehow and run it through exiftool (either command line or from e.g. http://exif.regex.info/exif.cgi). Or send it to me and I'll check.

**Comment by sahil-syze** [comment]
> Then that's probably because the camera or browser does not record `FocalLength` in the image

Yep that's right. On my macbook, I saved an image using PhotoBooth and parsed that image using the link your provided. It is missing the required exif tags.

_Bummer..._
