### ISSUE TITLE
Problem using ExifReader

### ISSUE THREAD

**Issue by jgautier2** [mattiasw/ExifReader#16]
Hello,

First, thanks for your useful script.

I'm using this piece of script to get IPTC tags of a file :
`var reader = new FileReader();

        reader.onload = function (evt) {            
            try {
                var exif = new ExifReader();

                // Parse the Exif tags.
                exif.load(evt.target.result);

                // Output the tags on the page.
                tags = exif.getAllTags();

            }
            catch (error) {
                alert(error);
            }
        };

        reader.readAsArrayBuffer(file);`

It works well.
Then I d' like to get and use tags's variable outside this piece of script, further in my script. But if I write console.log(tags) after the last line (after reader.readAsArrayBuffer(file);), variable is empty.

Could you please help me to solve this problem ?

Thansk a lot,

JG

**Comment by mattiasw** [comment]
Hi! Did you declare the tags variable outside the onload function? If not, try putting "var tags;" just below "var reader = new FileReader();".

**Comment by jgautier2** [comment]
Thanks for your answer.
I tried to put "var tags;" just below "var reader = new FileReader();", but I still can't use tags variable further in my script.
Let me tell you more about this script. I use [dropzone.js](http://www.dropzonejs.com) library, and I'd like to check IPTC before uploading images. So, I want to get and test IPTC when a file is added to dropzone, using dropzone's "added file" event, like that :

`
Dropzone.options.myDropzone = {

	init: function() {

	var dropzone = this;

	this.on("addedfile", function(file) { 
	    
		var reader = new FileReader();
		var tags;
	    	
		reader.onload = function (evt) {
				try {
						var exif = new ExifReader();
		
						// Parse the Exif tags.
						exif.load(evt.target.result);
						// Or, with jDataView you would use this:
						//exif.loadView(new jDataView(evt.target.result));
		
						// Output the tags on the page.
						var tags = exif.getAllTags();
						
					}
					catch (error) {
						alert(error);
					}
		};
		reader.readAsArrayBuffer(file);
			
	});
}};

`

First : if I put "console.log(tags);" just below "reader.readAsArrayBuffer(file);", tags appears "undefined".
In fact, I'd like to send tags data (converted to JSON) to a php script using ajax, but if I put an ajax call just below "reader.readAsArrayBuffer(file);", tags variable appears "undefined" so iptc_json POST variable is empty when received by the PHP script.
Here's my whole piece of script, with ajax call :

`
Dropzone.options.myDropzone = {    
    
    init: function() {

    var dropzone = this;

	this.on("addedfile", function(file) { 
	    
	    var reader = new FileReader();
	    var tags;
	    	
		reader.onload = function (evt) {
				try {
						var exif = new ExifReader();
		
						// Parse the Exif tags.
						exif.load(evt.target.result);
						// Or, with jDataView you would use this:
						//exif.loadView(new jDataView(evt.target.result));
		
						// Output the tags on the page.
						var tags = exif.getAllTags();
						
					}
					catch (error) {
						alert(error);
					}
		};
		reader.readAsArrayBuffer(file);
		
		var ajaxurl = 'ajax_verifyimage.php';  		
	   	var jqxhr = $.post( ajaxurl, { iptc_json: JSON.stringify(tags) }, function(data) {
				
			// test IPTC convenience	
			
		});
			
	});
}};
`

Could you please help me to understand what's wrong and how to fix it ?

Thanks a lot again,

JG

**Comment by mattiasw** [comment]
It's because the tags variable is not set at that point. Even though it may not look like it, the ajax call is run before the file and tags have loaded. Put the ajax call inside the try block instead, right after the exif.getAllTags().

**Comment by jgautier2** [comment]
All right, thanks, I understand.
Maybe if I make a synchronous ajax call (instead of asynchronous), It could work also ?
JG

**Comment by mattiasw** [comment]
In this case it wouldn't work. It's the file loading that would need to be synchronous (which is not possible as far as I know). But anyway, that's not recommended since it would lock the browser for the user.

**Comment by jgautier2** [comment]
Ok, thanks a lot for your help.

**Comment by mattiasw** [comment]
No problem.
