### ISSUE TITLE
Can't find resolution of one image

### ISSUE THREAD

**Issue by jgautier2** [mattiasw/ExifReader#166]
Hi Mattias,

I can't get PPP resolution (XResolution neither YResolution) of one image.

Image can be retrieve here :
http://site3.hanslucas.com/20211103_malandain_oiseauFeu_0162.jpg

Do you understand why ?

Thanks for your help.

JG

**Comment by mattiasw** [comment]
Hi! They seem to be part of a Photoshop tag group. That is currently not supported in ExifReader. I will have a look when I get the time and see how hard that is to implement.

**Comment by jgautier2** [comment]
Thanks a lot.
JG

**Comment by mattiasw** [comment]
Try version 4.1.0. It should show XResolution and YResolution for that image.
