### ISSUE TITLE
Can read img tag ?

### ISSUE THREAD

**Issue by hasban12138** [mattiasw/ExifReader#167]
```js
const img = document.createElement('img')
img.src = src
ExifReader.load(img)
```
It support？

**Comment by mattiasw** [comment]
Yes: https://github.com/mattiasw/ExifReader#let-exifreader-load-the-file-asynchronous-api

Like this:
```
ExifReader.load(img.src);
```

But the remote server has to set CORS headers that allow for remote loading of the file. Unless the file is on the same server as the web page.

**Comment by hasban12138** [comment]
Thanks!  
But I use like this:
```js
ExifReader.load(img.src).then((res)=>{
    console.log(res)
})
```
In browser I get this
![image](https://user-images.githubusercontent.com/33484052/142371201-f4fde997-6fbe-4c3e-8afd-bbb1036db75b.png)
It doesn‘t have exif
I use a worry way?

**Comment by mattiasw** [comment]
Can you share the file? I need it to be able to debug.

**Comment by hasban12138** [comment]
[img.zip](https://github.com/mattiasw/ExifReader/files/7561060/img.zip)
this is my image file

**Comment by hasban12138** [comment]
https://github.com/hasban12138/img
this is my file

**Comment by mattiasw** [comment]
I will have a look after work tonight.

**Comment by hasban12138** [comment]
Thanks!

**Comment by mattiasw** [comment]
When I try that image I can see the Exif info. Do you have the image on a web server somewhere that I can try to use directly? In case there is an error in the server setup.

**Comment by hasban12138** [comment]
During this time ,I try to find it too ,and I find this image has Exif but if I put it in Excel , it from Exif change to JFIF . That's why we can't find Exif
Thanks!
And by the way . Dose JFIF have Orientation  too ?

**Comment by mattiasw** [comment]
JFIF does not have orientation: https://exiftool.org/TagNames/JFIF.html
It may not help you but I'm working on better JFIF support. I hope to have it released within a week.

**Comment by hasban12138** [comment]
Thanks! My problem may not in Exif . Thank you very much !    : )
