### ISSUE TITLE
can't read IPTC tags in some images

### ISSUE THREAD

**Issue by jgautier2** [mattiasw/ExifReader#17]
Hi,

I can't read IPTC tags in this image, only EXIF tags are read:
http://hanslucas.com/ROJ07004MC022-06LITTLE.jpg

But I see them in Photoshop for example.

Can you help me to understand what's going wrong ?

Thanks a lot,

JG

**Comment by jgautier2** [comment]
Hi Mattias,

I'm sorry to insist, but I had some reading problems with this image also:
http://hanslucas.com/HL_CSHARROCK_LABOURPROTEST_28JUNE.jpg

There's a Creator tag in the file, but ExifReader doesn't recognize it.

Can you help me to understand what's going wrong or tell me if i can solve this problem by myself looking into the code ?

thanks for your answer,

JG

**Comment by mattiasw** [comment]
Hi! Sorry for taking so long, I have a lot to do right now and won't have time to look into this myself for probably several weeks (getting married next week and then going on our honeymoon :-) ). Maybe it has to do with ExifReader only supporting the non-XML format of IPTC and the image only have XML-formatted meta data. But I can't really say without looking into it more.

For the Creator tag, it may be easier. Probably you only need to add support for it in the code. If you have the specification, feel free to try.

**Comment by jgautier2** [comment]
Hi Mattias.
I hope you had a beautiful honeymoon !
Let me ask some more questions :
- I'd like to get "SubjectCode" tag using your tool : do you think there's a way to do that, or is it a XML formatted tag that ExifReader doesn't support ? (More : is there a chance that ExifReader supports XML iptc in a next version ?)
- If I want to add support for some more non-XML tags, could you tell me more about how to do it ? Where in the code do I have to search ?

Please feel free to answer me that you don't have time for that for the moment : I will understand and wait !

Thanks a lot,

JG

**Comment by mattiasw** [comment]
Hi! I thought I could get back to you earlier than this. :-) Anyway, both Creator and SubjectCode unfortunately seem to be from the XML version of IPTC. To develop a version that supports that would take some time and I can't promise anything about that. Sure, it would be nice to support it, but it's hard for me to get the time nowadays.

Adding support for more tags in the current code is easier though. Search for `'iptc':` in `src/ExifReader.coffee`. There you have an object with all available tags. The key is the hexadecimal tag ID. The value is either just the name, or the name and a function for how to parse the description field in the image file for that tag. If it's only the name, the description parsing will default to just using the raw bytes at the position in the file (converted to a string). Many tags just use the default description parsing. Check the IPTC specification to know how to do the parsing for the specific tag you want to add.

Please ask more questions if needed and I will do my best answering them.

**Comment by mattiasw** [comment]
@jgautier2 There is not support for the XML version of IPTC yet, but I've been doing some work here lately and just released a 2.0 version of the library. Next up will be to look into finally adding support for IPTC XMP. I have no idea how long it will take but with the restructuring that I did for 2.0 I think it will at least be easier than before. Maybe you already solved your needs for extracting meta tags but if not here's a heads up that it will hopefully come to ExifReader in the somewhat near future.

**Comment by jgautier2** [comment]
Thanks a lot.
JG

**Comment by mattiasw** [comment]
@jgautier2 I now have an implementation for parsing XMP tags in the branch iptc-xmp. Please try it out and give me your view of it. Since XMP tags are different, the format of the parsed tags is a little different. Please tell me if it looks strange, and if so how you would like to have it.

https://github.com/mattiasw/ExifReader/tree/iptc-xmp

**Comment by mattiasw** [comment]
I just merged this to master and will close this issue. Please file a new issue if there is something that looks strange.
