### ISSUE TITLE
Allow reading EXIF without loading whole image file into memory

### ISSUE THREAD

**Issue by phiresky** [mattiasw/ExifReader#174]
### Description

It's possible to read only parts of files using the `File / Blob` API via `Blob.slice(0, 1000)`, for example with the new [File System Access API](https://web.dev/file-system-access/).

It looks like ExifReader always uses FileReader to load the whole file into memory at once.

If I want to read the exif of e.g. 1000 10MB jpeg files, it would be great if ExifReader only had to read the actual 1kB of metadata instead of the whole image files. (like tools such as exiftool do)

**Comment by mattiasw** [comment]
Hi! This would definitely be a great thing. It's quite tricky to know how large the metadata is though, and as I've understood it it's not even certain it's always placed at the beginning of the file. There is a short note about this in the README. If you think it would work for your use case you can slice the buffer yourself before passing it in to ExifReader. It only uses FileReader if a file is passed in, an ArrayBuffer is also fine to pass. I think a good starting point is to read 128 K, but if you're only interested in Exif and don't care about IPTC, XMP etc. you may get by with less, but it will depend.

https://github.com/mattiasw/ExifReader#tips

**Comment by phiresky** [comment]
Yeah right now my initial hacky attempt was to just read the first 128kB of the file into an ArrayBuffer, then pass that. Seems to work so far, but it would be nice to have some guarantees and get away with less reading (e.g. i don't care about the thumbnail, which is probably by far the largest thing in the metadata?

**Comment by mattiasw** [comment]
I think guarantees are hard to get in this case. MakerNote can be huge for example, and ICC too (several megabytes). There was an earlier discussion about this and there one participant did an iterative thing. It was in Node but could be worth a try.

https://github.com/mattiasw/ExifReader/issues/53#issuecomment-548480740
