### ISSUE TITLE
No DateTimeOriginal property when using .HEIC data

### ISSUE THREAD

**Issue by nonoumasy** [mattiasw/ExifReader#176]
### Description

First of all, love the library. I have a web app hacktravels.com where the User can upload images. When I use the library on jpg files, it returns the tag descriptions but when I use it .heic image files, it doesn't show the "DateTimeOriginal" tag. I tried the demo, and on the demo works, ie it shows the DateTimeOriginal value. But I think thats because its in .heic format. So I think the issue maybe that since the files during upload cannot be .heic(its a web app), the .heic is automatically converted to jpg and, in this conversion, the exif data is lost and thus I can't access the exif data.

**Additional details**

- ExifReader version: "^4.1.1"
- Web browser and version: Chrome 97.0, also tested with Safari iOS 15
- Node version: 14.16.0
- Can you reproduce the bug on the examples site? If so, using which implementation (global object, AMD, and/or ES module)? https://mattiasw.github.io/ExifReader/  On the site, .heic format works! I can see the datetime.

**How to reproduce**
login on https://www.hacktravels.com/, create a journal and then add an entry using an .heic image

1.  
2.  
3.  

**What I expected would happen:**
I expect getting the DateTimeOriginal just like the demo

**What really happened:**
Nothing returned when selecting the .heic file

here is the code I'm using to extract the exif data:

```
export const getExifData = async (file) => {
  try {
    const tags = await ExifReader.load(file)
    delete tags["MakerNote"]
    const DateTimeOriginal = await tags["DateTimeOriginal"]?.description
    return DateTimeOriginal
  } catch (error) {
    console.log(error)
  }
}
```

**Comment by mattiasw** [comment]
Hi!

Are you doing this from an IOS device? There seems to be some issues where Apple has decided to strip metadata from images when they are uploaded to web sites. Some example discussions:

https://apple.stackexchange.com/questions/326789/gps-exif-from-iphone-photo-upload-in-safari
https://stackoverflow.com/questions/57942150/file-upload-and-exif-in-mobile-safari

If that is the issue it sounds hard to do anything about it except maybe not using HEIC.

If you do not believe that is the problem, could you attach or link to one of your HEIC files that I can try out myself? The ones I have do show `DateTimeOriginal`.

**Comment by nonoumasy** [comment]
Yes. I'm doing it from an iOS device. Thanks for those links. According the second link,  It does seem that if you use 
 'High Efficiency' then you are using .heic and that strips the exif data, while the 'Most Compatible' uses .jpg and that retains the exif data. In summary...
 
 .heic = no exif data
 .jpg = has exif data
 
And I can confirm, if I upload a jpg, I can get the DateTimeOriginal value, but if I use an .heic, this is does NOT get the DateTimeOriginal. I guess I'll have to bite the bullet on this one. It's a shame since adding datetime on my app is one of the most complex on my app, especially if its an old photo.
 
 Thanks again.

**Comment by nonoumasy** [comment]
I just confirmed this by going to the example site on iOS(should have done that earlier) and I tried uploading an .heic and it didn't strip all the Exif data, but it did strip the DateTimeOriginal.

<img width="605" alt="Screen Shot 2022-01-30 at 12 13 19 AM" src="https://user-images.githubusercontent.com/6312676/151692156-dbf0a0d3-df40-4b39-be8d-6915ba015886.png">

**Comment by mattiasw** [comment]
Sorry to hear that. A bit weird that there's a difference between the formats.
