### ISSUE TITLE
Get raw XMP data

### ISSUE THREAD

**Issue by tomgreco** [mattiasw/ExifReader#181]
### Description

Since this library is just for reading, it would be nice to be able to get the raw data. 
For example the XMP data, if I could get this as raw data I could then modify it and add new tags to it. 
Then using a different library write the XMP back to the file. 

Sorry if this functionality already exists but I couldn't find anything on it. 
I assume getting the raw data for other formats would be difficult but XMP seems pretty straight forward to me.

**Comment by mattiasw** [comment]
Hi,

Yeah, I think it should be pretty straightforward. I will have a look in the coming days.

**Comment by mattiasw** [comment]
This is now released as version 4.3.0. When using `expanded: true` the raw XMP string is accessible at `tags.xmp._raw`.

**Comment by tomgreco** [comment]
Thank you!
