### ISSUE TITLE
No longer compatible with React Native due to the use of https module

### ISSUE THREAD

**Issue by ybouane** [mattiasw/ExifReader#182]
### Description

Breaks on react native with error message:

```
error: Error: Unable to resolve module https from J:\[...]\App\node_modules\exifreader\dist\exif-reader.js: https could not be found within the project or in these directories:
  node_modules
```

**Additional details**

- ExifReader version: Latest (4.2.0)
- React native version: Latest (0.67.2)

**How to reproduce**
Create a basic react native project, install ExifReader and import it:
`import ExifReader from 'exifreader';`

The error will appear when reloading the RN app.

**Comment by mattiasw** [comment]
Hi,

I will have a look and see if React Native is easy to set up. In the meantime, does it make any difference if you import the non-transpiled source file instead? That is `node_modules/exifreader/src/exif-reader.js`.

**Comment by ybouane** [comment]
That has definitely helped! The error no longer shows up.
However, the GPS data is not retrieved from my test image.
Here's the image i've tested:
https://raw.githubusercontent.com/ianare/exif-samples/master/jpg/gps/DSCN0012.jpg

It does have GPS data, but when I run it through the library, the output is:

```
{
[...]

  "GPSLatitudeRef": {
    "id": 1,
    "value": [],
    "description": "Unknown"
  },
  "GPSLatitude": {
    "id": 2,
    "value": [
      [
        0,
        0
      ],
      [
        0,
        0
      ],
      [
        0,
        0
      ]
    ],
    "description": null
  },
  "GPSLongitudeRef": {
    "id": 3,
    "value": [],
    "description": "Unknown"
  },
  "GPSLongitude": {
    "id": 4,
    "value": [
      [
        0,
        0
      ],
      [
        0,
        0
      ],
      [
        0,
        0
      ]
    ],
    "description": null
  },
  "GPSAltitudeRef": {
    "id": 5,
    "value": 0,
    "description": "Sea level"
  },
  "GPSTimeStamp": {
    "id": 7,
    "value": [
      [
        0,
        0
      ],
      [
        0,
        0
      ],
      [
        0,
        0
      ]
    ],
    "description": "NaN:NaN:NaN"
  },
  "GPSSatellites": {
    "id": 8,
    "value": [],
    "description": ""
  },
  "GPSImgDirectionRef": {
    "id": 16,
    "value": [],
    "description": "Unknown"
  },
  "GPSMapDatum": {
    "id": 18,
    "value": [],
    "description": ""
  },
  "GPSDateStamp": {
    "id": 29,
    "value": [],
    "description": ""
  },
[...]
}
```

**Comment by mattiasw** [comment]
What device/simulator are you testing this on? If you use the browser on that device, does it work here for the same image? https://mattiasw.github.io/ExifReader/esm/

**Comment by ybouane** [comment]
I’m using an Android simulator (Pixel 5).
The web version works perfectly fine, so maybe the OS is stripping the GPS information when the app loads the image? (Is there a special permission that needs to be requested to avoid that?)

**Comment by mattiasw** [comment]
I took some time and got React Native running (very easy with Expo!) and confirmed that the suggested import worked. I've added more React Native instructions to the README file about it so that should be clear now at least.

Regarding missing GPS details I'm afraid I don't know if there could be any special permissions needed, but I would make sure to allow the app to get access to the device's location in case that spills over to any used photos. I've also seen a lot of people in various threads around the internet having trouble getting GPS details in React Native when using regular Exif libraries. And different people seem to have different experiences with both Android and IOS so I'm not sure what to believe here.

Also see this issue which is about the same problem, with a suggestion to look at a native library which probably has more power in this regard: #177

**Comment by ybouane** [comment]
Thanks for your help mattias, I appreciate it :)

**Comment by nschild** [comment]
@mattiasw any idea on how to get the typescript typings to import automatically?

**Comment by mattiasw** [comment]
@nschild Sorry, I don't. I haven't used it with TypeScript myself and I wasn't the one that added the typings to the library so I never tried it.

**Comment by a-vikor** [comment]
## To work with remote images:

Hello,

First of all, thank you for the library :) While inspecting the issues I noticed that the maintainer/owner does an outstanding job.

To work with remote images in a TypeScript React Native project:

1.  Use the import described in readme file in your file where you are about to interact with image metadata:

        import ExifReader from '../../../../../../../node_modules/exifreader/src/exif-reader.js';

    This will cause your TS complain as there are no declaration files for the package inside `/src` folder.

2.  To solve TS issue, head to `node_modules/exifreader` and copy the `exif-reader.d.ts` file to the `/src` folder of the package. The issue should be gone.

3.  Attempting to read image metadata with help of

        const tags = await ExifReader.load(url);

    will fail. The issue is located inside `browserFetchRemoteFile` function of `exif-reader.js` at the line:

        return fetch(url, options).then(response => response.arrayBuffer());

    **response.arrayBuffer()** will throw `FileReader.readAsArrayBuffer is not implemented` exception. You can [read about this issue here](https://github.com/facebook/react-native/issues/34402).

    To overcome the issue, add a `get` function below the `browserFetchRemoteFile` function:

        function get(url) {
          return new Promise((accept, reject) => {
          var req = new XMLHttpRequest();
          req.open('GET', url, true);
          req.responseType = 'arraybuffer';

          req.onload = function () {
            var resp = req.response;
            if (resp) {
              accept(resp);
            }
          };

          req.send(null);
          });
        }

    And call it inside the browserFetchRemoteFile with the `url` parameter:

        function browserFetchRemoteFile(url, {length} = {}) {
          return get(url);
          // const options = {method: 'GET'};
          // if (Number.isInteger(length) && length >= 0) {
          // options.headers = {
          // range: `bytes=0-${length - 1}`,
          // };
          // }
          // return fetch(url, options).then(response => response.arrayBuffer());
        }

4.  Lastly, patch your package with `yarn patch-package exifreader` and have a nice day :)

**Comment by mattiasw** [comment]
Great research!

I was wondering if it would help if I placed a duplicate `exif-reader.d.ts` inside `/src` when publishing the npm package? Do you think there could come any problems from that?

**Comment by tomgreco** [comment]
I was able to solve this by replacing any require(https) | require(http) lines with require(axios) and it seemed to work fine.
