### ISSUE TITLE
Does the image need to be in HEIC?

### ISSUE THREAD

**Issue by ianharoldonwater** [mattiasw/ExifReader#185]
In your readme, you show the format as HEIC. Can it be jpg?

<img width="901" alt="Screen Shot 2022-03-10 at 10 32 02 AM" src="https://user-images.githubusercontent.com/89031726/157721432-6b220dd3-eca7-4cf4-95f5-2e42dff78c8e.png">

**Comment by mattiasw** [comment]
Yes, definitely. PNG, TIFF, and WebP also work. There is a support table at the top of the README if you want more details.
