### ISSUE TITLE
Version 4.4.0: error TS2304: Cannot find name 'File'

### ISSUE THREAD

**Issue by slongiaru-rblab** [mattiasw/ExifReader#188]
### Description

Compiling projects using ExifReader version 4.4.0 the issue is:

../../node_modules/exifreader/exif-reader.d.ts(182,37): error TS2304: Cannot find name 'File'.

File is not defined in types.

Issue is under: exif-reader.d.ts

https://github.com/mattiasw/ExifReader/blob/7effa200f026b8beabe29b5fee6cf1e5ecac2cd9/exif-reader.d.ts#L182

**Additional details**

- ExifReader version: 4.4.0
- Web browser and version: all
- Node version: all

**How to reproduce**

yarn install
lena run build

**Comment by mattiasw** [comment]
😖 I shouldn't have touched the typings when I don't know TypeScript. Do you happen to know the correct way to use `File` to get it working? It's the `File` present in a browser context. I tried to google it but apparently failed.

**Comment by mattiasw** [comment]
Do you have a more specific procedure for reproducing this? I'm trying to set up a project that would fail building but it seems to work fine for me.

**Comment by alez007** [comment]
@mattiasw not lib's fault, the importer needs to make sure they have `lib: ["dom"]` listed in their tsconfig.json so the File type would be correctly found by typescript

**Comment by mattiasw** [comment]
Thank you @alez007! Then I'm closing this.
