### ISSUE TITLE
interface Tags does not have a `Thumbnail` property

### ISSUE THREAD

**Issue by wangjianio** [mattiasw/ExifReader#190]
Is that right?

https://github.com/mattiasw/ExifReader/blob/9629a051ae44af7a4a0b467694aef88c976df605/exif-reader.d.ts#L193

![image](https://user-images.githubusercontent.com/11157726/162815505-9b7f5214-14fc-4aaf-b3a4-5ed1e4f368d1.png)

**Comment by mattiasw** [comment]
TypeScript type definitions have been added by others than me and they depend a lot on users of the library to keep them up-to-date. That being said, if this PR looks correct I can make a release with it: #191

**Comment by wangjianio** [comment]
Thankfully, it looks right.
Next time I will make the PR 🙏

**Comment by mattiasw** [comment]
Great! It's released as 4.5.0.
