### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by ts-neumann** [mattiasw/ExifReader#199]
Is it somehow possible to make the ExifReader able to read out special Characters- like the german (ä, ü etc.) properly?

Tested it with exifreader v 4.5.0 on my own system and on your hosted example website
https://mattiasw.github.io/ExifReader/esm/

- Browserversion Google Chrome Version 103.0.5060.134

Screenshot:
https://i.imgur.com/x2674Ho.png

[Testfile](https://teamcloud365-my.sharepoint.com/:i:/g/personal/thorsten_schneider_login_officecloud_site/ERrJZXzAGgVDlKNRvcmqKyAB3veoYuRatcKbdj_j79q_Jg?e=pmTEQu)

**Comment by mattiasw** [comment]
Hi! It should already do that. The text stored in the file should use UTF-8 though, does it? When I try the test file with exiftool it also gives `Dˆrr` (exiftool is an awesome command line tool for reading image metadata).

**Comment by ts-neumann** [comment]
Oh ok my bad then. Maybe its already wrong in the file then. Should have checked that before. Thank you for the quick response!

**Comment by mattiasw** [comment]
Check it and re-open this ticket if the problem persists. For reference, similar questions has been asked before (and solved) in #26, #36, and #45.
