### ISSUE TITLE
Get timezone of image

### ISSUE THREAD

**Issue by qwerty287** [mattiasw/ExifReader#200]
### Description

Hello,
it looks like ExifReader doesn't read timezone information. The `DateTime` tag contains the time in the timezone it was taken, but not the zone itself. It would be really cool if I could get the timezone too. I had the same problem with exif-js already, they don't parse it as well. Exiftool is able to parse it, but not every tag date/time shows the timezone. Thanks!

**Comment by mattiasw** [comment]
Hi! The time zone (time offset) for when the picture was taken can be found in the tag called `OffsetTimeOriginal`. Does that work for your photo?

**Comment by mattiasw** [comment]
No problem at all!
