### ISSUE TITLE
Please add support for Flir Tags 

### ISSUE THREAD

**Issue by ericoporto** [mattiasw/ExifReader#21]
It would be great to be able to read Flir EXIF data from images - I really would like to be able to extract the embedded Flir images along with their info like it can be done with Phil Harvey's Exiftool. 

http://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/FLIR.html

**Comment by mattiasw** [comment]
Interesting. Do you have one or a couple of example images that I can test with?

**Comment by ericoporto** [comment]
https://commons.m.wikimedia.org/wiki/File:Man_in_water_-_IR_image.jpg

This is an example image, I will search for more and place here (I don't have my camera right now)

**Comment by mattiasw** [comment]
Thanks. I'll try to look into it when I've finished support for XMP metadata. Having a couple of images to look at and test with will help when I start.

**Comment by mattiasw** [comment]
So, this seems to be a proprietary format encoded in the Maker Note tag in the JPEG. I would say that is a bit specialized for this library (wanting to keep file size down is one reason). But if one would want to do it, ExifReader can easily be used to extract the raw Maker Note data as a start.
