### ISSUE TITLE
GPSImgDirection is typed as a number but outputs an array

### ISSUE THREAD

**Issue by mkabatek** [mattiasw/ExifReader#219]
### Description

Is typed as a number - but outputs an array.
`'GPSImgDirection'?: NumberTag,`

**Additional details**

- ExifReader version: 4.9.1
- Web browser and version: Chrome Version 109.0.5414.87 
- Node version: v18.13.0
- Can you reproduce the bug on the examples site? If so, using which implementation (global object, AMD, and/or ES module)? https://mattiasw.github.io/ExifReader/

**How to reproduce**

![Solocator-2022-08-17-13-43-43](https://user-images.githubusercontent.com/1764486/221375697-2798907e-0b98-40b4-82e4-edba638e15c1.jpg)

```   
 // --- parse exif data --- //
    const exif = exifReader.load(img.Body as Buffer)

    console.log(exif)
    
    const {
      GPSLatitude,
      GPSLatitudeRef,
      GPSLongitude,
      GPSLongitudeRef,
      GPSAltitude,
      GPSImgDirection,
      RelativeAltitude,
      GimbalYawDegree,
      GimbalPitchDegree,
      DateTime,
      Software
    } = exif
```

Output:

```
`GPSImgDirection: { id: 17, value: [ 8, 1 ], description: '8' },`
```

**Comment by mattiasw** [comment]
Thanks for the report! Fixed and released in version 4.9.2.
