### ISSUE TITLE
No shutter count in output

### ISSUE THREAD

**Issue by salivity** [mattiasw/ExifReader#220]
there is no shutter count in the output object, where other online services correctly extract this information.

**Comment by mattiasw** [comment]
Hi! Do you have an example image that contains this value? And one of the online services you've used that displays this may also help. It sounds like shutter count is located inside the camera manufacturers' proprietary data fields and not the standardized metadata locations but I will have another look when I have an image to test with.

**Comment by salivity** [comment]
i used https://www.metadata2go.com/ but the output from my site has no shutter count, https://davidclews.com/article/57.html
![DSC00060](https://user-images.githubusercontent.com/94751817/223402126-49ae448b-710d-42cc-8b02-839ff3fd50fa.JPG)

**Comment by salivity** [comment]
probably would suit a kind of normalized function across the variations of this data. eg sony, nikon and canon variations

**Comment by mattiasw** [comment]
As I expected the shutter count is located inside the MakerNote tag and that content's format is specific to each device (or at least each manufacturer). To add support for that would be a lot of work and for a front-end library I believe it would also make the code too big. If this value is important I can see a couple of paths forward:
- Parse the file on the server.
- Try to find a library that parses the MakerNote tag. ExifReader makes it easy to extract the MakerNote data so it can still be used as a part of that solution if this new library does not have support for reading the other metadata.
- If another library can't be found, create a new one that can parse this info. From a quick web search it looks like at least some of the manufacturers' formats have been reverse engineered and have specifications online.

Sorry I can't be of more help.

**Comment by mattiasw** [comment]
Closing as out-of-scope.
