### ISSUE TITLE
Adding exif support for PNG?

### ISSUE THREAD

**Issue by HoverBaum** [mattiasw/ExifReader#221]
Love to see a still active project for Exif data 🎉

**Any thoughts on or plans for supporting Exif in PNGs?**

I am building a tool to explore "generation parameters" of images generated using Stable Diffusion. The data I need is stored in Exif and I currently use: https://github.com/MikeKovarik/exifr to extract that. But the repo is sadly unmaintained.

Repo I am working on: https://github.com/HoverBaum/sd-params

**Comment by mattiasw** [comment]
Hi! Yeah, I've seen a couple of libraries appear and then die down over the years since I started on this in 2012. No plans to stop working on this one though. :-)

I have been thinking about Exif for PNG actually but I haven't been able to find many example image files to test it on. Do you have any? I guess I only need one to get started.

P.S. That's a cool project that seems handy.

**Comment by HoverBaum** [comment]
Here are two example images. 
I hope uploading it to GitHub keeps the exif.

For my use case, I am especially interested in the non-standard field `"parameters"`.

# Basic example

![00001-3540802589](https://user-images.githubusercontent.com/7557414/224258028-7b0ef374-af5a-42f7-8946-ebdd45ffaa8b.png)

What I would expect to see:

```JSON
{
  "ImageWidth": 1024,
  "ImageHeight": 1024,
  "BitDepth": 8,
  "ColorType": "RGB",
  "Compression": "Deflate/Inflate",
  "Filter": "Adaptive",
  "Interlace": "Noninterlaced",
  "parameters": "Portrait of a giant, fluffy, ninja teddy bear, hood, intense, intimidating, excitement, danger, intrigue, dramatic lighting, high-contrast, dgtl\nNegative prompt: watermark, signature, plain background, horrific, mutated, monster, gross\nSteps: 98, Sampler: DDIM, CFG scale: 7, Seed: 3540802586, Size: 648x648, Model hash: 1976397d3d, Model: model, Denoising strength: 0.47, Mask blur: 4, SD upscale overlap: 64, SD upscale upscaler: ESRGAN_4x"
}
```

# A special case for me

Another interesting case for me is the following image. It contains `"` in the value of a field. Not sure if that is only special for my parsing logic or could have any impact for extracting the exif.

![00246-1523377376](https://user-images.githubusercontent.com/7557414/224259149-9e6bc6e6-aabd-4fe2-8b53-80313502cb4a.png)

```JSON
{
  "ImageWidth": 1024,
  "ImageHeight": 1024,
  "BitDepth": 8,
  "ColorType": "RGB",
  "Compression": "Deflate/Inflate",
  "Filter": "Adaptive",
  "Interlace": "Noninterlaced",
  "parameters": "dgtlv2, character portrait of a female human, cyberpunk, shadowrun, megacorporation forest, anxious, dramatic, backlight lighting\nNegative prompt: watermark, signature, plain background, horrific, mutated, monster, gross, anime\nSteps: 30, Sampler: DDIM, CFG scale: 8.5, Seed: 1523377376, Size: 512x512, Model hash: 1976397d3d, Model: v2.1-512, Denoising strength: 0.55, Wildcard prompt: \"dgtlv2, character portrait of a __gender__ __metahuman__, cyberpunk, shadowrun, __location-modifier__ __location__, __mood__, __mood__, __light__ lighting\", Hires upscale: 2, Hires steps: 20, Hires upscaler: 4x_foolhardy_Remacri"
}
```

**Comment by mattiasw** [comment]
Those images worked fine, and no issues with the `"` from what I could see. The new feature handling these tags has been released as version 4.10.0.

As a side note and technical detail (and for me to remember later), `parameters` wasn't stored as an Exif tag but as `tEXt` PNG textual data where tags can be stored with any name.

**Comment by HoverBaum** [comment]
Amazing!

Works great in my project 😁
It was an easy [drop-in replacement](https://github.com/HoverBaum/sd-params/commit/116394eb32bda943726b785192b13764000d750b).

Thank you so much for picking this up!

Should the Readme be updated now to mention Exif support for PNGs?

**Comment by mattiasw** [comment]
Nice!

The `parameters` value was not stored as Exif data so it wasn't support for Exif in PNGs that I added, and I wasn't sure how to represent that in the support table. That being said, I continued on during the weekend and added real Exif support so now it is mentioned too in the README.

**Comment by himuro-majika** [comment]
Hi.
I'm happy to see that you support the PNG tEXt chunk.
I'm also working with images generated by Stable Diffusion.
PNG parameters generated by Stable Diffusion may contain Unicode or non-ASCII characters.
So, is it possible to resolve the garbled non-ASCII characters?
A sample image is attached for reference.

![25763-2269788512-table, 😺 🐶 食](https://user-images.githubusercontent.com/5001278/224578028-100f5b9b-9093-41ec-9ad0-1ad4d4d67c13.png)
The sample parameters are as follows

`"table, 😺 🐶 食\nNegative prompt: easynegative,\nSteps: 20, Sampler: DPM++ 2M Karras, CFG scale: 5, Seed: 2269788512, Size: 512x512, Model hash: f9077799a9, Clip skip: 2"`

**Comment by mattiasw** [comment]
When I read the specification again it clearly says iTXt chunks are encoded using UTF-8, so they should of course be decoded as such. Thanks for pointing it out. A fix is released in version 4.11.0. These are great additions to the library. Thank you both for helping out!

**Comment by himuro-majika** [comment]
I have verified the fixes.
Thank you for your great work!

**Comment by mattiasw** [comment]
Sure. `value` is supposed to be the actual byte values from the file and `description` is a more readable/formatted form of that. `value` is there for people that want to format the tag value in some other way, e.g. image orientation that is a number in the file but is shown as a descriptive text in `description`. In this specific case it's not as clear what the difference would be so I settled on not doing the UTF-8 decoding for `value`. I guess another way would be to use the byte array in `value` and not making a string of it at all. For data that is shown to end users I think `description` is most often the way to go.

**Comment by HoverBaum** [comment]
Sweet, thanks for the explanation. I was confused between the two and went for "value", will switch to "description".

Also, what a good distinction for this case could be. Maybe a thing to revisit once we learn what we would like to do with it.

Closing for now as the initial feature request is implemented 😁
