### ISSUE TITLE
Add support for data URLs to the load function

### ISSUE THREAD

**Issue by mbucc** [mattiasw/ExifReader#223]
### Description

Add support for [data URL's](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs) to `load(url)`.

While this is relatively easy to work around, it would be nice if this was implemented in the library.

This is the work around I landed on:

      fetch(dataurl)
          .then( (y) => y.arrayBuffer() )
          .then( (data) => {
              var file = new File( [ data ], urlFileName );
              const tags = ExifReader.load(file)
                  .then(...

My use case was to use exif reader from Elm code.  Due to how Elm enforces its type system guarantees when interacting with non-Elm Javascript, I had to pass the uploaded file as an integer array or a data URL.  I chose an URL because from reading the exif reader docs, I thought reading a data URL would be supported.

**Comment by mattiasw** [comment]
Hi! Thanks for the great suggestion. I'm almost done but couldn't fully finish it today.

**Comment by mattiasw** [comment]
Now it's released as version 4.11.0.

**Comment by mbucc** [comment]
I should be able try it out next week end.  Thanks!
