### ISSUE TITLE
Typescript definitions problem

### ISSUE THREAD

**Issue by AndriiHarashchak** [mattiasw/ExifReader#229]
After adding this library to my angular 14 application, I`m getting thess errors:
![image](https://user-images.githubusercontent.com/63160844/225642353-1ba6af4a-df59-4e2c-90f9-f960c9e92536.png)

To fix it, I added **| any ** to last two properties types, and it helped:
`interface PngTags extends PngFileTags {
    'Pixels Per Unit X'?: NumberFileTag
    'Pixels Per Unit Y'?: NumberFileTag
    'Pixel Units'?: 'meters' | 'Unknown' | any
    'Modify Date'?: NumberArrayFileTag  |any
    [name: string]: PngTag
}`

**Comment by mattiasw** [comment]
Fixed and released as version 4.11.1. Thanks for reporting! I added some automatic type testing to avoid this in the future.
