### ISSUE TITLE
[Question] Is there a way to remove all metadata?

### ISSUE THREAD

**Issue by ternaus** [mattiasw/ExifReader#234]
Is there a way to remove all metadata from `jpg`, `tiff`, `webp`, `png`, `heic` files?

**Comment by mattiasw** [comment]
Hi! Writing to a file is not possible with ExifReader. But if you're in a web browser environment I believe it's not that hard to do by writing the image to an HTML canvas and then saving the canvas as a new image file. That would automatically remove all meta data.
