### ISSUE TITLE
Add support for zTXt

### ISSUE THREAD

**Issue by jseagull** [mattiasw/ExifReader#236]
### Description

NovelAI store promt in zTXt like this image
![008](https://user-images.githubusercontent.com/2908639/236615001-3b0be440-2911-4efe-9dd5-aa060adf10b4.png)

Are there plans to support zTXt? Or support in nodejs only with zlib?

**Comment by mattiasw** [comment]
Hi! I've had some ideas around this and it seems doable. I will give it a try.

**Comment by mattiasw** [comment]
I finally got this working. Released as 4.20.0. Make sure to pass in `async: true` in the options parameter if you're not already using the async version.
