### ISSUE TITLE
Complains about DataView when in Electron

### ISSUE THREAD

**Issue by greggman** [mattiasw/ExifReader#24]
I tried using this in electron and I see this error

<img width="804" alt="screen shot 2017-07-26 at 23 43 53" src="https://user-images.githubusercontent.com/234804/28627305-59d4d684-725c-11e7-98d9-d67e78eba2a6.png">

Even though I'm using it in a browser view (meaning it's Chromium with a normal browser level DataView implementation)

Is that expected?

**Comment by greggman** [comment]
So the issue is `DataView` in the browser doesn't work with `Buffer` (which doesn't exist in the browser but does exist in Electron). The solution was to change the nodejs example from

    const tags = ExifReader.load(data);

to

    const tags = ExifReader.load(data.buffer);
     
Which *should* work in both cases assuing JDataView also takes typed arrays and not just Buffers.

**Comment by mattiasw** [comment]
Fixed in #25. Thanks for contributing @greggman.
