### ISSUE TITLE
ExifReader reads file type wrong

### ISSUE THREAD

**Issue by madhurakhal** [mattiasw/ExifReader#246]
### Description

It seems that for few file types it cannot read the correct file type. I test on .png file but it reads as `image/jpeg`

![MicrosoftTeams-image (2)](https://github.com/mattiasw/ExifReader/assets/839882/6f7caf2d-db7a-4ec9-ab48-8d75dbf73eaf)

**Comment by mattiasw** [comment]
Hi! That file is a JPEG image. It's the filename extension that is wrong.

**Comment by madhurakhal** [comment]
If you try to save the image it says png. It's wired...
