### ISSUE TITLE
Basic support to detect WebP Animation

### ISSUE THREAD

**Issue by cjandrews** [mattiasw/ExifReader#247]
### Description

Loading a few different webp files with animations seems to fail, such as these:

https://colinbendell.github.io/webperf/animated-gif-decode/webp.html

It would be great to be able to at least see that it's a WebP with animation.

Not sure if this is a bug, but...

**Additional details**

- Web browser and version: On latest Chrome 116.0.5845.111

- Can you reproduce the bug on the examples site? If so, using which implementation (global object, AMD, and/or ES module)? 

Yes, I was able to reproduce this with the Global Object Example using this URL (and a few other tries):

https://colinbendell.github.io/webperf/animated-gif-decode/4.webp

**How to reproduce**

Try the link or any of the examples from here: https://colinbendell.github.io/webperf/animated-gif-decode/webp.html

**What I expected would happen:**

At least simple output stating that it's a WebP with animation

**What really happened:**

Message that there is no metadata. See screenshot:

![image](https://github.com/mattiasw/ExifReader/assets/5743476/e518af80-55a9-4106-8a01-cfa09e41d6d2)

Thanks for taking a look!

**Comment by mattiasw** [comment]
Hi! It looks like that shouldn't be too hard to add. I have another thing I want to add first but then I will have a look at this. I will have some extra spare time during September.

**Comment by cjandrews** [comment]
@mattiasw That would be great. Thank you. I'm seeing webp animations become more common as there's greater browser support and as people realize the quality is so much better than GIF if  you don't want a movie file.

Thanks again.

**Comment by mattiasw** [comment]
There is a PR for this now if you want to try it out. It shows if the WebP file has an animation or not. It will only show the tag if the file is using extended WebP format but as I understand it only those files can have animation.

I'm planning on merging and releasing during the coming days if nothing comes up.

https://github.com/mattiasw/ExifReader/pull/253

**Comment by mattiasw** [comment]
Released as version 4.14.0.

**Comment by cjandrews** [comment]
@mattiasw Thank you! I have been a bit tied up but will try this out. Best regards.
