### ISSUE TITLE
Incorrect encoding of ImageDescription and title

### ISSUE THREAD

**Issue by zdila** [mattiasw/ExifReader#26]
Please see picture from comment at https://github.com/FreemapSlovakia/freemap-v3-react/issues/206#issuecomment-330638605

ExifReader returns for `Object Name` correct string `Amonova Lúka` but for `ImageDescription` and `title` it returns incorrectly `Amonova LÃºka`.

Sites like https://www.thexifer.net/ and http://metapicz.com/ and also exiftool shows the string correctly for all fields.

**Comment by mattiasw** [comment]
It seems the encoding used in that file is not according to spec. For Exif, the `ImageDescription` tag can only have ASCII text and does not support multi-byte characters ("Two-byte character codes cannot be used. When a 2-byte code is necessary, the Exif Private tag UserComment is to be used."). Also, for the XMP tags (`Title`) I can't see how one would find the encoding of the XMP data, or for a specific string inside it, if it's not UTF-8.

That being said, it may be okay to convert all strings and hope that it won't mess anything up. I have done that in a pull request (#29) that I hope you can take a look at to see if it fixes your encoding problems.

**Comment by mattiasw** [comment]
Fixed in #29.

**Comment by zdila** [comment]
Thank you! Could you please also update npm package?

**Comment by mattiasw** [comment]
I thought I did that. Didn't it work? Version 2.1.2.

**Comment by zdila** [comment]
I apologize, now it works for us. Not sure why it didn't reflect on our production server before but after redeployment it now works.

Thank you.

**Comment by mattiasw** [comment]
👍
