### ISSUE TITLE
Incorrect exposure time reported for description

### ISSUE THREAD

**Issue by edwardhorsford** [mattiasw/ExifReader#270]
### Description
I have an image where the `tags.ExposureTime.description` appears to be reporting the wrong value.

The complete property is:
```js
ExposureTime: { id: 33434, value: [ 15, 10 ], description: '2' },
```

I'm presuming the `value` is a rational expression so 15/10 = 1.5 seconds. If I look at the image in Lightroom, that's also what's reported.

On a hunch this was related to exposure times of a second or more, I have logged out the `tags.ExposureTime` on all images that don't include a `/` in the description. Of 800 images I have several more occurrences. Whole second exposure times seem ok, but not 1.x exposure times:

```js
{ id: 33434, value: [ 13, 10 ], description: '1' } // should be 1.3s
{ id: 33434, value: [ 15, 10 ], description: '2' } // should be 1.5s
```

**Additional details**

- ExifReader version: Latest (4.2)
- Web browser and version: N/A
- Node version: 20 on MacOS
- Can you reproduce the bug on the examples site? If so, using which implementation (global object, AMD, and/or ES module)? https://mattiasw.github.io/ExifReader/

**How to reproduce**

I'd rather not upload an image here, but can provide one directly if that's helpful.

**What I expected would happen:**

The description appears to be a string representation of a fraction - for 1.5 seconds I would expect `"1.5"`.

**What really happened:**

Got a value of 2 seconds.

**Comment by mattiasw** [comment]
Hi! I seem to have no test images with this kind of exposure time. That could be why I haven't noticed it before. So it would be helpful to get an example picture. Feel free to crop to 1x1 and remove any sensitive metadata.

**Comment by edwardhorsford** [comment]
Thanks for looking at this so quickly!

Attaching an example image with 1.5s exposure time.
![ENMH_D800_44176](https://github.com/mattiasw/ExifReader/assets/2204224/2facd2c7-8a1f-4a23-ae4b-885fed059912)

**Comment by edwardhorsford** [comment]
It seems like _most_ times under 1s are expressed as rational expressions of 1/x. I've now logged out all images where `tags['ExposureTime'].value[0] !== 1` - and have a case of the `description` being wrong below 1s too:
```js
{ id: 33434, value: [ 8, 10 ], description: '1/1' }
```

I think this should probably have a value of 0.8?

Thinking about it more, I suspect this bug might exist for all values > 0.5s and <2s?

**Comment by mattiasw** [comment]
Yeah, that's deliberate. It's a bit tricky to guess how people want this value to be represented. From earlier discussions, values below 1 have been preferred to be expressed like 1/800 e.g. The issue with that is that the 800 is not always exactly 800, so there is some rounding (I think there was a good example where this was wanted). If it's smaller numbers this will get weird as you've noticed. If I'm uncertain I usually try to mimic how exiftool does this but you are showing numbers I haven't come in contact with before. :-) It would be great if you could run your images with weird descriptions through exiftool (`exiftool -G image.jpg`) and look at the `[EXIF]` value for `Exposure Time` and post the results here. I did it for the image above and it unsurprisingly gives me 1.5. This seems like an obvious change to make. But it would be nice to have a good set of rules for the other situations too.

**Comment by edwardhorsford** [comment]
Sure thing! Exif tool gives:
```
[EXIF]          Exposure Time                   : 0.8
```

FWIW, for anything above 0.5s I don't think you can reasonably output a fraction - 4/5s just doesn't sound right - I think all cameras would say 0.8s. I suspect you could remove all rounding for any times over 0.5s?

**Comment by mattiasw** [comment]
Let's try that. There is a PR now if you want to have a look: #271

**Comment by mattiasw** [comment]
Busy week. But now this is published as version 4.21.0. See PR for more details: #271

**Comment by edwardhorsford** [comment]
Thanks for resolving this so quickly!

**Comment by edwardhorsford** [comment]
Have upgraded locally and can confirm for my above image the time is now showing as 1.5s. Closing this as resolved.
