### ISSUE TITLE
Feature request: AVIF format

### ISSUE THREAD

**Issue by 7freaks-otte** [mattiasw/ExifReader#273]
As the AVIF image format is now supported in all major browsers (even in Edge since Jan 26, 2024) I'd love to see it supported in ExifReader.

From my understanding the container format is HEIF and as HEIC is already supported, AVIF could probably be implemented fairly easy.

Browser Support: https://caniuse.com/avif
AVIF syntax and semantics: https://aomediacodec.github.io/av1-avif/
At least image_height and image_width seem to be inherited by HEIF: https://aomediacodec.github.io/av1-avif/#biblio-heif

**Comment by mattiasw** [comment]
Hi! AVIF support is actually at the top of my list of new functionality I want to add (after a couple of bug fixes). Thanks for letting me know there is interest in it. I will try to prioritize it in the coming weeks.

**Comment by 7freaks-otte** [comment]
Thank you, that is really good news @mattiasw 🙌🏼

**Comment by mattiasw** [comment]
This is finally starting to look good (had to re-implement, the HEIC code was very naive). If you have any images I can test on that would be appreciated. I only have a few I created myself and they may not be representative.

**Comment by mattiasw** [comment]
Released as 4.22.0.
