### ISSUE TITLE
Feature Request: Support for MOV, MP4, etc

### ISSUE THREAD

**Issue by mwargan** [mattiasw/ExifReader#274]
Hey, we're evaluating using this package for reading EXIF data client-side.

Do you plan to support other file formats that have EXIF data, like MOV or MP4 files? The examples page says they are not if type image (obviously), but is it planned?

https://exif.tools/ shows that the files I tested do indeed include EXIF data.

**Comment by mattiasw** [comment]
Hi! It's not planned for the near future but I'm open to the idea.

**Comment by johnsyin** [comment]
Hi, did anyone find any alternative for this?
