### ISSUE TITLE
Error with image in AVIF format

### ISSUE THREAD

**Issue by Forest33** [mattiasw/ExifReader#289]
### Description

```
Error: Illegal byte order value. Faulty image.
    at Object.getByteOrder (byte-order.js:20:11)
    at Object.read (tags.js:19:33)
    at loadView (exif-reader.js:246:31)
    at loadFromData (exif-reader.js:181:12)
    at exif-reader.js:44:63
```

**Additional details**

- ExifReader version: 4.22.0
- Web browser and version: Google Chrome 123.0.6312.86

### Example AVIF image

https://photouz.uz/wp-content/uploads/2024/04/2g8a0686-uluchsheno-um.avif

![](https://photouz.uz/wp-content/uploads/2024/04/2g8a0686-uluchsheno-um.avif)

**Comment by mattiasw** [comment]
Thanks for reporting! Fix was just released as version 4.22.1.
