### ISSUE TITLE
The width and height of the image are incorrectly obtained

### ISSUE THREAD

**Issue by besscroft** [mattiasw/ExifReader#299]
### Description

expect:

![image](https://github.com/mattiasw/ExifReader/assets/33775809/f2e551aa-4af7-4f00-b31b-add688475343)
actually:
<img width="1280" alt="b17f45d70ca2f6790e5d781593da1163" src="https://github.com/mattiasw/ExifReader/assets/33775809/184b4470-a74f-4790-b3e0-6647166c26b2">

**Additional details**

- ExifReader version:^4.22.1
- Web browser and version: Chrome 123.0.6312.123
- Node version:v20.11.1
- Can you reproduce the bug on the examples site? If so, using which implementation (global object, AMD, and/or ES module)? https://mattiasw.github.io/ExifReader/

**Example Image File**

![FDAB0C214A002CE64F2C3C3F63E425B9](https://github.com/mattiasw/ExifReader/assets/33775809/df629b65-3471-4687-9182-a5da845048fe)

**What really happened:**

I found that the width and height values read for my vertical photo were incorrect.

Finally, thank you for your work. I hope you can help me figure out the problem, thank you!

**Comment by mattiasw** [comment]
Hi! I guess you realized already but it's because of the rotation/orientation. The image is actually landscape but web browsers and other tools often auto-rotate.
