### ISSUE TITLE
Lens model doesn't seem to be parsed correctly

### ISSUE THREAD

**Issue by LaurenceHo** [mattiasw/ExifReader#300]
### Description

Lens model doesn't seem to be parsed correctly. I use PhotoScapeX to inspect my photo, I can see the lens model metadata, however, "LensModel" is empty by using ExifReader.

**Additional details**

- ExifReader version: 4.22.1
- Web browser and version: Microsoft Edge Version 123.0.2420.97 (Official build) (64-bit)
- Node version: v20.11.1
- Can you reproduce the bug on the examples site? If so, using which implementation (global object, AMD, and/or ES module)? https://mattiasw.github.io/ExifReader/

**How to reproduce**

1.  Uploaded photo to https://mattiasw.github.io/ExifReader/esm/
2.  I didn't see LensModel on the tag list, however, it exists since I can see it from another software (PhotoScapeX)

![Screenshot 2024-04-20 102659](https://github.com/mattiasw/ExifReader/assets/7505861/0b6c92e3-385a-485c-8dd4-0fa8a31f5e1e)

**What I expected would happen:**

I should be able to see the value inside the LensModel tag.

**What really happened:**
There is no LensModel tag.

![Screenshot_20-4-2024_102541_mattiasw github io](https://github.com/mattiasw/ExifReader/assets/7505861/05f7426d-aac3-49f3-8bec-735f404c8199)

**Comment by LaurenceHo** [comment]
I checked another repo which relates to ExifTags too:
https://github.com/python-pillow/Pillow/blob/f8160b858aebf8b7bffdefba48735feac300a060/src/PIL/ExifTags.py#L206

and this is yours

https://github.com/mattiasw/ExifReader/blob/ac01b16e657a94b605a1cc54ff6b217809d7bd77/src/tag-names-exif-ifd.js#L370

Both of them are basically identical. Have any idea about this?

**Comment by mattiasw** [comment]
Hi! There are several possible reasons for this. I need the image to be able to investigate.

**Comment by LaurenceHo** [comment]
Ciao! I think this issue is a bit tricky. Today I just realised that I could see the lens model from other photos taken from another camera (Canon). Just let you know about this. I can send you the photo if you'd like to investigate.

**Comment by mattiasw** [comment]
Please do if you can. It would be interesting to see why this happens for this photo.

**Comment by LaurenceHo** [comment]
> Please do if you can. It would be interesting to see why this happens for this photo.

Hi, I uploaded 4 photos to my demo album website
https://d3lfuof5usiolc.cloudfront.net/album/2024/demo-album5

4 of them all have lens model information, however, only 2 of them can display lens models on the website. Feel free to download the photos. Thanks.

**Comment by mattiasw** [comment]
Thanks! The reason the lens model is not visible in two of the images is because the camera has put it in the maker notes which is a camera-specific proprietary field which does not follow any common metadata specification. It would unfortunately be both too much work and make the package too big to support all of those.

**Comment by LaurenceHo** [comment]
> Thanks! The reason the lens model is not visible in two of the images is because the camera has put it in the maker notes which is a camera-specific proprietary field which does not follow any common metadata specification. It would unfortunately be both too much work and make the package too big to support all of those.

Thanks for the prompt investigation!! I now have some clues, I may make it work on my side. :D

**Comment by mattiasw** [comment]
In case it's helpful in any way it may be worth mentioning that it is possible to extract the raw binary data for the maker notes using ExifReader.
