### ISSUE TITLE
How to extract metadata from HTMLImageElement?

### ISSUE THREAD

**Issue by a0s** [mattiasw/ExifReader#305]
### Description

So, i have an HTMLImageElement() or already loaded Image()

```ts
const image = new Image()
image.src = '...'
image.onload = function() {
 ExifReader.load(...) ????
}
```
How can i get exif inside callback? I didn't find any example in readme or missed it?

**Comment by mattiasw** [comment]
Hi!

Here are a couple of previous questions about the same thing:
https://github.com/mattiasw/ExifReader/issues/184
https://github.com/mattiasw/ExifReader/issues/167

The summary is that you have to load it again with `ExifReader.load(image.src)` which should take the image from the browser cache. Make sure the server is setting the correct CORS headers or that the image is located on the same server as the page.

**Comment by a0s** [comment]
Thank you, it works perfect!
