### ISSUE TITLE
lens_specification read value overflow

### ISSUE THREAD

**Issue by besscroft** [mattiasw/ExifReader#320]
### Description
lens_specification read value overflow

**Additional details**

- ExifReader version:^4.23.1
- Web browser and version:Chrome 124.0.6367.208
- Node version:v20.11.1
- Can you reproduce the bug on the examples site? If so, using which implementation (global object, AMD, and/or ES module)? https://mattiasw.github.io/ExifReader/

**Example Image File**
![20240325-DSC_0399 (1)](https://github.com/mattiasw/ExifReader/assets/33775809/08fc3c19-012e-49af-a50b-435c98d2db8a)

**What I expected would happen:**
"16-50 mm f/6.3"

**What really happened:**
![image](https://github.com/mattiasw/ExifReader/assets/33775809/9cfdf036-3e8a-481a-a260-2af6fea894c7)

Finally, thank you for your work. I hope you can help me figure out the problem, thank you!

**Comment by mattiasw** [comment]
Hi!

That looks like the common JavaScript problem with floating-point number representation, the reason that also makes 0.1 + 0.2 = 0.30000000000000004.

I'll see if I can add some code to detect when it happens and round it.

**Comment by mattiasw** [comment]
Fixed and released as version 4.23.3.
