### ISSUE TITLE
Would you consider a less restrictive license?

### ISSUE THREAD

**Issue by mike-marcacci** [mattiasw/ExifReader#33]
Hi there! Firstly, thanks so much for making this library – it's definitely my favorite of the available EXIF readers published to npm.

I'm hoping to use it in a project where the LGPL license would be a bit problematic. While I *could* probably full it from a CDN to constitute a "dynamic link" and avoid the copy-left requirements, I'd much rather pull it into my webpack bundle.

Would you consider relicensing this under something more permissive, such as the [MIT](https://opensource.org/licenses/MIT) license?

Thanks again!

**Comment by mattiasw** [comment]
I'm very glad to hear that you like the library. I never meant to stop people from using it the way you describe. That's why I originally chose LGPL over GPL. At that time npm was not a big thing (at least not for me) and using a script tag was probably how you would include a 3rd party script on your page.

However, even though I didn't think of this scenario when the license was chosen, after some additional research I still believe it's okay for you to bundle it using webpack. Please tell me if I'm missing something in my following reasoning. (It may not apply if you're making a smartphone app or something like an Electron app.)

The important part here is that the user of your application should be able to "re-link" the library in your application to use another version. This being the web and JS code being quite easy to identify even when minified, that is absolutely doable. (It could be different with WebAssembly though, or if you are doing something other than using it on a web page.) I think this answer in the GPL FAQ explains the situation:

https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic

Do you agree with me? :-) (I'm not totally against changing licenses, but it seems like LGPL should work here. Then also, it may not if you're making something other than a web page...)

**Comment by mike-marcacci** [comment]
Hey Mattias,

Thanks so much for the speedy and thorough reply, and sorry for my slow response – I’ve had limited internet access over the past couple days.

Following your explanation, I definitely agree that LGPL wouldn’t be a problem when building a webpack bundle for a client-side web app, which is awesome since this is my current need! I would like to mention, though, that in the next couple months, we’ll be porting this app to mobile devices using react native. While I still have to do a bit of research to confirm this suspicion, I don’t think the same rationale would hold true in this this case. I’ll do a bit more digging and comment back.

Thanks so much again for the library and your time!

**Comment by mattiasw** [comment]
I agree with you, LGPL will not allow the library to be used in a closed-source mobile app. At least not without a lot of hassle from the app developer. I will change the license. Not sure to which one yet though. I like everything else about the LGPL and I think e.g. MIT would be too permissive. I would like to make sure changes get back to the community e.g. If you have a suggestion for a license, please tell me.

**Comment by mike-marcacci** [comment]
Awesome! The Mozilla Public License may have that right balance. Reading it myself this wasn’t 100% clear, but the summary at https://choosealicense.com/licenses/ suggests that it is less limiting on “larger works.”

**Comment by mattiasw** [comment]
After reading up on MPL it sounds perfect. Thanks!

**Comment by mattiasw** [comment]
Updated and published.

**Comment by mike-marcacci** [comment]
Thanks so much @mattiasw!

**Comment by mattiasw** [comment]
What are the reasons for not including MPL in that list, if you don't mind talking about it? From what I understand, MPL generally works well side by side with those licenses.

**Comment by mjcampagna** [comment]
Our situation is a little unique because we ship this code in a desktop app to clients, it's not just hosted in a browser. Here's what Google's AI says about it:

> When distributing a desktop app using code licensed under the Mozilla Public License (MPL), **you can ship the compiled executable without necessarily including the full source code with it, as long as you make the source code readily available online and clearly inform users where to access it**; this means you can "ship" a desktop app with just the compiled binary while still complying with the MPL's requirements regarding source code availability.

We don't want to have to make our source code available publicly just because we include a single MPL dependency.

**Comment by mike-marcacci** [comment]
Hi @mjcampagna – I think you're misunderstanding the license terms. Your situation isn't unique; code is published and distributed in equivalent ways for mobile apps and single-page web apps all the time.

Of course, read [the actual license](https://github.com/mattiasw/ExifReader/blob/main/LICENSE) for yourself, but my fairly informed (but non-legal, non-advise) understanding of MPL 2.0 is that its copy-left provisions only apply to the licensed code itself and any direct modifications you make to the licensed code, but _not_ an entire "larger work" that includes the licensed code.

You should have your legal team review the license again and check out [Mozilla's FAQ on the license](https://www.mozilla.org/en-US/MPL/2.0/FAQ/).

**Comment by mjcampagna** [comment]
@mike-marcacci It’s our legal that’s advised us on what licenses we can use. Looking at the license, I think this is the problem. It does seem to me that by including this code in our project, we are meant to make our own project source available. 

> 3.2. Distribution of Executable Form
> 
> If You distribute Covered Software in Executable Form then:
> 
> (a) such Covered Software must also be made available in Source Code
>     Form, as described in Section 3.1, and You must inform recipients of
>     the Executable Form how they can obtain a copy of such Source Code
>     Form by reasonable means in a timely manner, at a charge no more
>     than the cost of distribution to the recipient; and

**Comment by mattiasw** [comment]
@mjcampagna You only have to make available the source code of the MPL-licensed files, not you own files. The [MPL's FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) that @mike-marcacci linked is pretty good at answering these questions. Specifically Q11 is relevant here:

> Q11: How 'viral' is the MPL? If I use MPL-licensed code in my proprietary application, **will I have to give all the source code away?**
> **No.** [...] This allows, for example, programs using MPL-licensed code to be statically linked to and distributed as part of a larger proprietary piece of software[.]

**Comment by mjcampagna** [comment]
Thanks. I'll pass along to our legal guys and see whether this satisfies their concerns.
