### ISSUE TITLE
Difference in GPS output on Desktop and Android.

### ISSUE THREAD

**Issue by Raketten1963** [mattiasw/ExifReader#378]
- ExifReader version: 4.23.3

Hi there,

I know this has been discussed before, but I am quite sure my problem is different.

I use webpack to do a simple PWA where I make a call to load for a file, and get the results back.
All is fine on desktop, while on Android load returns a lot of NaN for the GPS values.

I tried the examples, and they return the values just fione on both desktop and android.

Is anybody else seeing this behaviour?

KInd Regards Henrik

**Comment by Raketten1963** [comment]
I just build a minimum sample and put it at https://exif.ipdb.plus and it does not fail on Android.

THis lead me to suspect that it is somehow unhappy with living with some of the other modules I use, so I will start adding them one by one and see what is happening.

Any pointers are super welcome...

**Comment by Raketten1963** [comment]
It appear to have to do with the input element type=file, which will strip GPS info if you include the accept="" in the input element. If you skip that, you will get your GPS info....sigh

**Comment by mattiasw** [comment]
Wow, what a find. I wonder what the reason is for that, especially if you can get around it by not setting the `accept` attribute. Sorry for not being of any help, but I don't think I would have guessed this was the reason.

**Comment by mattiasw** [comment]
I added this info to the README and linked to this thread: https://github.com/mattiasw/ExifReader#gps

**Comment by Raketten1963** [comment]
Thanks Mattias,

I think you should change the type="File" accept="image/*" as this is what will make it fail, see below


<input type="file" name="myImage" accept="image/*" />

I think this will help many people moving forward.

I am not sure if this also apply to iOS, but I think having the text there, will help people on iOS anyway, as they might try out removing the 'type' specification.

Kind regards Henrik

________________________________
