### ISSUE TITLE
Add a files section in package.json to restrict the files installed?

### ISSUE THREAD

**Issue by greggman** [mattiasw/ExifReader#38]
If I understand correctly if you add a 

    "files": [
      "dist/exif-reader.js",
      "dist/exif-reader.js.map"
    ],

To package.json then when installing this a dependency all the examples would stop being included in other projects. 

I noticed all the images from this library were in my electron project when did a search for .jpg in the root of my project to find my own images and all of the examples in this project showed up.

**Comment by mattiasw** [comment]
Wow, I didn't realise it included all files by default. I'll fix!

**Comment by mattiasw** [comment]
#39 should fix this. Thanks for the issue report!

**Comment by mattiasw** [comment]
Fixed in #39.
