### ISSUE TITLE
GPSLatitude / GPSLongitude have wrong typescript definitions

### ISSUE THREAD

**Issue by zivni** [mattiasw/ExifReader#388]
First of all, great job. I'm enjoying your library.

the exif properties GPSLatitude / GPSLongitude are defined in typescript as `NumberArrayTag`  which is `TypedTag<number[]>`. But it should be `TypedTag<number[][]>` as the value is 3 items array of a 2 dimensions array. 

So to be precise the definition should be `GPSLatitude? : TypedTag<[[number, number],[number, number],[number, number]]>`.

I don't have enough knowledge on Exif to know if this is only on the GPS or are there any other fields that are this way.

**Comment by mattiasw** [comment]
Hi!

Thanks for the report. You are absolutely right, and there actually already is an issue for it, #288, I just haven't had time to look at it yet. But I'm going to fix it right away and use your suggestion. I'm closing this as a duplicate in the meantime.

**Comment by mattiasw** [comment]
And no, I can't think of any other tags off the top of my head that could have the same type problem, but I did notice that `GPSAltitude` also had the wrong type, `NumberTag` instead of the correct `RationalTag`.
