### ISSUE TITLE
Expand for IPTC?

### ISSUE THREAD

**Issue by markusproske** [mattiasw/ExifReader#4]
Matthias, I really like your ExifReader, good work! 

I'm currently setting up some kind of online travel stories with no cms/server behind, so it can be served from any webspace or dropbox/google drive. I started using your ExifReader on the client side to enhance the picture descriptions with metadata like exposure, iso, ... . Next step would be to automatically label the pictures with IPTC Headline or other IPTC fields such as IPTC Creator.
I did some research on this topic finding http://code.flickr.net/2012/06/01/parsing-exif-client-side-using-javascript-2/ and http://stackoverflow.com/questions/5833026/extract-iptc-information-from-jpeg-using-javascript but I did not find any js-library to embed for reading EXIF+IPTC.

Do you have any plans to continue/expand ExifReader?

Cheers,
Markus

**Comment by jdolan** [comment]
I used this branch to read IPTC tags from Associated Press images and it worked well. Thanks!

**Comment by mattiasw** [comment]
That's nice to hear!

**Comment by jgautier2** [comment]
Hi (again),

Is there a way to read more IPTC tags ?
I'm trying to get some "creator"'s tags like "Creator's CI: City", etc., but ExifReader doesn't seem to do that, does he ? 
The best could be to manage all tags from "2014 IPTC Photo Metadata Standard" (IPTC Core + IPTC Extension), i.e. all IPTC tags in this image : [https://www.iptc.org/std/photometadata/examples/IPTC-PhotometadataRef-Std2014_large.jpg](url)

thanks for your answer and help.

JG

**Comment by jgautier2** [comment]
Hi Mattias,

If you have a moment, could you please also answer me to this question above ?

You could just tell me if there's a chance to do that, and if possible how.

thanks,

JG

**Comment by mattiasw** [comment]
Hi! See my answer in #17. It's definitely possible to read more tag, they just have to be added to the code. Me personally don't really have the time right now though.

**Comment by mattiasw** [comment]
This has been merged into the master branch now. #20
