### ISSUE TITLE
Fork with some IPTC support enhancements

### ISSUE THREAD

**Issue by SaintFlipper** [mattiasw/ExifReader#42]
I've extended/improved ExifReader's IPTC tag support in fork https://github.com/SaintFlipper/ExifReader, as we needed it for our project (I'm working in the news picture industry).
These seem like generally useful extensions if you want to merge them into the master branch.

1. So it decodes text by honouring a specified "coded character set" encoding signal (1:90) if TextEncoder is available (native or [polyfill](https://github.com/inexorabletash/text-encoding))
This allows ExifReader to handle many of the character sets listed in the [IPTC IIM specification](https://www.iptc.org/std/IIM/3.0/specification/IIMV3.PDF) Appendix C, most usefully the iso-8859-x charsets and utf8.
Note that IPTC IIM v3 specification states that in the absence of a coded character set (1:90) dataset the application should assume ISO 646 IRV (aka ASCII). In practice many
recent implementations assume UTF8, but that's an informal and non-standard usage.

2. So that the IPTC dataset (aka field number) is available through tag.id in addition to the descriptive label in tag.description.
This is so an application can extract specific fields of interest from the IPTC tag list using the official dataset ID (eg. headline = 2:105 = 617) rather than
the English language description (which presumably might change).

3. Extending the set of supported datasets to include records 1 and 7, so the application has access to fields such as destination, service ID, and product ID.

4. Added further JPEG marker IDs to image-header.js#isAppMarker(), allowing the parser to iterate over segments such as SOFn and COMMENT which occur before other segments of interest (APP13, EXIF, XMP).
Previously the parseAppMarkers loop would break out at that point so the ability to extract EXIF/XMP/IPTC metadata was dependent on the segment order.

**Comment by mattiasw** [comment]
Those are some great improvements indeed. I would definitely like to merge them. I have some comments though, like regarding tests and some other smaller things. I would not mind fixing these things myself, then I'll learn better what you did, but please tell me if you're keen on doing it and I'll be more specific.

**Comment by SaintFlipper** [comment]
Thanks Mattias. I did consider adding to your unit tests, but fell at the
first hurdle as on Windows *npm test* fails with "*'BABEL_ENV' is not
recognized as an internal or external command*". I suspect you are better
placed to add or modify the unit tests as you know what's there already,
and what level of test cover you're aiming at. I'm very happy to assist
though, for example if you need samples of iso-8859-x and utf8 encoded iptc
datasets.
Any code which I've touched will be commented so hopefully easy to
understand, but please do let me know of anything which isn't clear or if
I've missed any areas which are independent of ExifReader.load() and its
dependencies.

**Comment by SaintFlipper** [comment]
Mattias, I finally got around to this.

a) A set of test JPEG files with various character set encodings is now in
https://github.com/SaintFlipper/ExifReader/tree/master/test_files
For each JPEG file there's a corresponding .js file defining the IPTC data block (starting at the initial 0x1C marker, so no Photoshop 0x404 resource or APP13 marker), the headline (as Unicode) which is present in encoded form in the IPTC 2:105 (aka 617) dataset, and a fabricated destination (dataset 1:05 aka 261) in case you want to test for a record 1 field.

FYI: The JPEG which all the samples were created from is my own, with no copyright restrictions. The headline (and caption) used in each file is from the "I can eat glass" samples at http://kermitproject.org/utf8.html 

b) I also added a new example directory under examples/dragdrop which provides a drop&drop demo for ExifReader, displaying the JPEG as a thumbnail, and a categorised (IPTC/EXIF/XMP) listing of the extracted fields, including the IPTC dataset ID, for example 2:105 for the headline. I guess it's similar to examples/global, just friendlier to use and displays the IPTC dataset IDs in addition to the description.
This demo page uses AngularJS and Bootstrap, all remotely CDN hosted, and I've made it viewable using Github Pages (which I only just found out about) at
https://saintflipper.github.io/ExifReader/examples/dragdrop/

Let me know if you need any changes to the test files, or anything else. For example I can probably generate the full APP13 segment, or the Photoshop resource block, if that works out better for testing.

**Comment by mattiasw** [comment]
Thanks! Those helped making sure everything is correct. I have been working on tests and some refactoring in this branch: #46

I did some smaller changes to the output of your code but I hope they don't matter too much.

- I have used upper case letters for encoding names before so I changed to `ISO-8859-X` instead of `iso-8859-X`.
- I added one or two spaces to some of the new tag names to follow the other names: `Short Document ID`, `Unique Document ID`, `Owner ID`

If you want, have a look at what I did and come with suggestions. Otherwise, if you don't have any comments on that I will merge it.

**Comment by SaintFlipper** [comment]
Yes, I think your changes look fine. On the encoding names I'd previously kept 'description' and 'encoding_name' separate so they could diverge if necessary, but it looks like the Encoding specification (https://encoding.spec.whatwg.org/) allows either case so it should be OK using the common upper case name you've refactored into getEncodingName.

Are you planning to include the drag&drop example? Useful to have an interactive demo that can run directly from Github I think.

**Comment by mattiasw** [comment]
:+1: It should be easy enough to split `description` and `encoding_name` up if needed, but it's a good point. Regarding the drag'n'drop example it's nice but feels like quite large for this very specific library. I will consider putting up a smaller live example page on GitHub Pages though. That is probably good to have.
