### ISSUE TITLE
XMP character encoding issue

### ISSUE THREAD

**Issue by bpatrik** [mattiasw/ExifReader#45]
Hi,

I found a potential bug within the XMP tags:
I try to read the face regions that lightroom generate to a photo ([in nodejs](https://github.com/bpatrik/pigallery2/blob/54781ee667d13f9a9deeed216ad97c047e3ccba8/backend/model/threading/MetadataLoader.ts#L176)):
attribute `mwg-rs:Name` within `ExifReader.load(data).Regions.value.RegionList.value[i].value['rdf:Description'].attributes['mwg-rs:Name']`

The name should be `special_chars űáéúőóüío?._:` but instead I get: `special_chars Å±Ã¡Ã©ÃºÅÃ³Ã¼Ã­o?._:`

Do you have any recommended solution for fixing it?

I'm using the following jpg for testing:

![test image ouooueau-](https://user-images.githubusercontent.com/7512182/51438629-e85ff200-1cae-11e9-8d0f-3f586acfc764.jpg)

Thanks!

Best,
Patrik
p.s.: really nice lib, thanks for the great work!. The only things that bothers me that with nodejs it has dependencies like `jdataview` that is needed to be somewhat 'mock'.
(And also Typescript type definitions would be nice :) )

**Comment by mattiasw** [comment]
Hi Patrik,

Thanks for the bug report. Can you try this branch? #47

**Comment by bpatrik** [comment]
Hi,

I can confirm that #47 works, thank you for the quick work!

That would be awesome!

**Comment by mattiasw** [comment]
Merged. Will do a publish to npm later. Thanks again for the report!

**Comment by mattiasw** [comment]
@bpatrik I don't know if the tagging worked in the PRs (your name was not auto-completed) so mentioning it here too. There are now two new PRs regarding your other suggestions: #48 and #49.

**Comment by bpatrik** [comment]
Hi,

Yes I saw them. Thank you very much!
I'll check both of them today/tomorrow.

Patrik
