### ISSUE TITLE
部分标签信息好像没有获取到

### ISSUE THREAD

**Issue by yanshanshu** [mattiasw/ExifReader#451]
![DJI_20241217115303_0006_V](https://github.com/user-attachments/assets/f3d3116b-ff92-4a12-9615-ac24fba1804b)
关于图片的标记和备注标签没有获取到，没有找到single; 和0.9.142的值

**Comment by mattiasw** [comment]
Hi! Thanks for the report. A fix has been released as version 4.26.0.
