### ISSUE TITLE
Missing exif tags

### ISSUE THREAD

**Issue by avnermosh** [mattiasw/ExifReader#51]
I have a jpg image where I can see some tags via exiftool (see below),
but when running the exif-reader example I'm getting a message complainign that there is no exif data
```
  message: "No Exif data"
  name: "MetadataMissingError"
```

How can I extract the image with, height and file modification time in such case?

Thanks

---

```
exiftool  default_image.jpg  
ExifTool Version Number         : 10.80
File Name                       : default_image.jpg
Directory                       : /home/sh3d
File Size                       : 829 bytes
File Modification Date/Time     : 2019:02:12 23:57:36-08:00
File Access Date/Time           : 2019:02:21 20:49:34-08:00
File Inode Change Date/Time     : 2019:02:12 23:57:36-08:00
File Permissions                : rw-rw-r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : None
X Resolution                    : 1
Y Resolution                    : 1
Image Width                     : 300
Image Height                    : 300
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 300x300
Megapixels                      : 0.090
```

**Comment by mattiasw** [comment]
Hi,

It looks like the file does not have any exif data in it. I think all of the details listed from exiftool above can be extracted from the image data itself, no need for any exif block. Width and height could probably be added to ExifReader, but for modification time I think it belongs somewhere else (mostly because that is a file system property and will not be found in the file itself and that's out of the scope of this library).

**Comment by avnermosh** [comment]
Thanks for replying.
I see another js package <https://github.com/exif-js/exif-js> Do you know
if it is complementary to ExifReader or is it another implementation?
Thanks again,
Avner

**Comment by mattiasw** [comment]
It's another implementation. It looks like it does not support Node.js though, which I guess is what you want since you want to read file system properties.

**Comment by mattiasw** [comment]
I've added some of the metadata tags that you listed above, more specifically Image Width, Image Height, Bits Per Sample, Color Components, and Subsampling (those are part of the JPEG specification). If you are still interested, please have a try and see if you can get the info you want.

**Comment by barcor** [comment]
Hi, I can't see tags GPSLongitude and GPSLatitude from safari or Chrome iOS on iPhone ??? Please help me

**Comment by mattiasw** [comment]
Hi! IOS usually removes those tags for privacy reasons and there is nothing the web application can do about it. That being said, please try to upload the image from your phone on another online Exif parser and get back to me if you can see the GPS position there, e.g. http://exif-viewer.com/ or https://jimpl.com/.

**Comment by barcor** [comment]
Hi

Thank's for responding.
