### ISSUE TITLE
npm package doesn't include exifreader.d.ts

### ISSUE THREAD

**Issue by ChaosinaCan** [mattiasw/ExifReader#54]
When I install ExifReader with npm using `npm i exifreader`, exifreader.d.ts is not included in the package. I have to manually copy it from this repo into my project to get TypeScript types to work.

**Comment by mattiasw** [comment]
Fixed in 2.8.2 which should soon be visible on npm. Thanks for pointing it out. Shout if this for some reason still doesn't work.

**Comment by ChaosinaCan** [comment]
Thanks!
