### ISSUE TITLE
Can't get some XMP tags from some images

### ISSUE THREAD

**Issue by jgautier2** [mattiasw/ExifReader#55]
Hi Mattias,

I have some difficulties to get some tags from some images (but not all).
For example, I try with this image : http://juliengautier.net/HL_ENASSY_VELEDISCAMPIA_8.jpg

Using ExifReader, I can't get Subject Code, neither Country Code, neither Marked status, neither WebStatement. But these tags are present in the file, and both Photoshop ans ExifTool can read them.

This problem doesn't happen with all files. For example, Exif Reader reads everything correctly in this other file : http://juliengautier.net/TEST_COPYRIGHT_PROTEGE.jpg
I can't understand why.

Thanks for your help,

JG

**Comment by mattiasw** [comment]
Hi! I'm on a trip for a couple of weeks. Will look at it when I'm back home.

**Comment by mattiasw** [comment]
Hi again! It should work now. The image metadata contained an empty array value which broke the parsing. Thanks for helping making ExifReader better!

**Comment by jgautier2** [comment]
Thanks a lot !
JG
