### ISSUE TITLE
GPS info question

### ISSUE THREAD

**Issue by fasei** [mattiasw/ExifReader#65]
my picture gps info :
Latitude: 38;54;11.2115470000136952
Longitude:115;27;37.3150630000163375

but I got gps info is:
Latitude: 38;54;11.211547
Longitude:115;27;37.315063

Can you help me?

**Comment by mattiasw** [comment]
Do you have an example image I can look at?

**Comment by fasei** [comment]
You can use this picture:
https://s2.ax1x.com/2019/11/13/M8Iq91.jpg

**Comment by mattiasw** [comment]
I had a look at this and to me it seems like ExifReader shows the correct value. My suspicion is that it's a precision error in the other tool you use. I get the same as you with exiftool for example. The coordinates are stored as a quotient in the image file (in the example picture it's 13834533 / 1000000 for the latitude seconds, so correct value would be 13.834533, which is what ExifReader shows). The value retrieved using a tool will depend on how the tool handles floating point divisions. To try this out I wrote a C program that divided 13834533 with 1000000 like in the example picture and that gave me 13.83453300000000041337. So it really looks like a precision error, especially when your example numbers have multiple zeros in the middle.
