### ISSUE TITLE
undefined-42034 can you name it?

### ISSUE THREAD

**Issue by Scan0815** [mattiasw/ExifReader#66]
### Description
Some unnamed Tags

### result from ExIfReader

https://dumpz.org/aHgHtZ3X6TyE

`undefined-42034:
description: (4) [18, 200, 3.5, 6.3]
id: 42034
value: (4) [18, 200, 3.5, 6.3]
__proto__: Object
undefined-42036:
description: ["18-200mm F3.5-6.3"]
id: 42036
value: ["18-200mm F3.5-6.3"]
__proto__: Object`

### Todo
can you name it? 
like 
     LensSpecification: [ 4.15, 4.15, 2.2, 2.2 ],
     LensMake: 'Apple',
     LensModel: 'iPhone 6 back camera 4.15mm f/2.2' 

thx

**Comment by mattiasw** [comment]
I can! 🙂 Thanks for pointing out that it's missing.

**Comment by Scan0815** [comment]
top! thanks for you work!

**Comment by Scan0815** [comment]
Maybe you need the exif codes:
0xa432 | LensInfo | rational64u[4] | ExifIFD | (4 rational values giving focal and aperture ranges, called LensSpecification by the EXIF spec.)
0xa433 | LensMake | string | ExifIFD |  
0xa434 | LensModel | string | ExifIFD |  
0xa435 | LensSerialNumber | string | ExifIFD

**Comment by mattiasw** [comment]
Thanks, always good with confirmation. I will probably push new code with the tags tomorrow.

**Comment by mattiasw** [comment]
I pushed a new branch for this, including a lot of other missing tags (#67). If you have time, feel free to try it out. I will publish it later today.

**Comment by Scan0815** [comment]
perfect, i add the branch and it work!
thanks, for the fast add.

regads Oliver

**Comment by mattiasw** [comment]
Published to npm now.
