### ISSUE TITLE
Problem reading Webstatement and Marked Tags

### ISSUE THREAD

**Issue by jgautier2** [mattiasw/ExifReader#68]
Hello,

I've a problem while reading Webstatement and Marked Tags on some pictures.

These two pictures contains these two tags (Photoshop shows them).
But ExifReader gets these two tags of the second picture only, not the first one.

First image : http://hanslucas.com/test/first.jpg (tags not OK)
Second image : http://hanslucas.com/test/second.jpg (tags OK)

I can't figure why...
Do you have an idea ?

Thanks a lot,

JG

**Comment by mattiasw** [comment]
Hi! I'll try to have a look later today.

**Comment by mattiasw** [comment]
Apparently there is something called Extended XMP. It is used when the size of the XMP data segment is too large (64K). In that case it's split into multiple segments. There is currently no support for that but I will look into it.

**Comment by jgautier2** [comment]
Thanks a lot Mattias.
JG

**Comment by jgautier2** [comment]
Perfect : it works. Thanks a lot.
JG
