### ISSUE TITLE
HEIC exif data support?

### ISSUE THREAD

**Issue by Anima-t3d** [mattiasw/ExifReader#72]
### Description

I don't see any [HEIC](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format) support for exif data? Will it be implemented?

There is a [fork from exif-js](https://github.com/exif-heic-js/exif-heic-js) that supports HEIC:
https://github.com/exif-heic-js/exif-heic-js/blob/master/exif-heic.js#L525-L570

**Comment by mattiasw** [comment]
Hi! I could have a look at it. Do you have one or two example images that you know have metadata in them?

**Comment by Anima-t3d** [comment]
You can [use this tool to check the data](http://exif.regex.info/exif.cgi)
You can [use this link to download a .heic file with exif data](https://drive.google.com/file/d/1owYSKgH4ngcnwJQq7izOrdRnYG9n0cOb/view?usp=sharing)
