### ISSUE TITLE
Replace exif.js?

### ISSUE THREAD

**Issue by narenpublic** [mattiasw/ExifReader#73]
### Description

exif.js is no longer maintained and I encountered a js bug on exif.js line 741 because n is not declared.

Can you switch to ExifReader? 

https://github.com/mattiasw/ExifReader

**Comment by mattiasw** [comment]
What do you mean? This is ExifReader. :-)

**Comment by narenpublic** [comment]
🤦‍♂️

sorry! was meant for https://github.com/digitalascetic/ngx-pica
