### ISSUE TITLE
Using exifReader in AWS S3 Lambda

### ISSUE THREAD

**Issue by sudhar99** [mattiasw/ExifReader#74]
I want to read the EXIF (specifically XMP) data of files being written into AWS S3. When I use the following (after reading from s3 getObject call);

```
var exifData = exif.load(response.Body, {expanded: true});
 listTags(exifData);
function listTags(tags) {
        for (const name in tags) {
            console.log(`${name}: ${tags[name].description}`);
        }
    }
```

I get the following message:
file: undefined
exif: undefined
xmp: undefined

But the same works fine in browser upload (fs reader). How can I make this work with raw buffer in AWS?

**Comment by arnav13081994** [comment]
Hi,

I was facing the same issue. Most likely you are not reading the files correctly and Exif is failing silently.

Doing this fixed it for me

```
var files = e.target.files; // This is basically the filelist object. 
for ( file of files) {
    let reader = new FileReader();
    reader.onload =  function (readerEvent) {
       try {
	      let tags =  ExifReader.load(readerEvent.target.result);
	      coordinates_array.push( { 'lat':tags['GPSLatitude'].description, 'lng':tags['GPSLongitude'].description } );
                // After getting the coordinates delete tags as it can have a huge memory imprint.
		delete tags;

	} catch (error) {
			console.log("EXIF failed: ", error);
	}
     };
	  reader.readAsArrayBuffer( file );
}


```

**Comment by mattiasw** [comment]
@sudhar99 I think this is your issue: When using `expanded: true` the result comes back segmented into file, exif and xmp properties like this: `{"file": {...file tags...}, "exif": {...exif tags...}, "xmp": {...xmp tags...}}`. Your loop tries to get the description on the wrong object, you have to go one step deeper in the structure. If you're only interested in the XMP data, change to this and it should work: `listTags(exifData.xmp);`
