### ISSUE TITLE
It would be nice if Exif takes into account GPSLatitudeRef and GPSLongitudeRef and returns the sign adjusted Lat, Long values

### ISSUE THREAD

**Issue by arnav13081994** [mattiasw/ExifReader#75]
### Description

**How to reproduce**

1. Run Exif on any JPEG image that has Location info
2. Get the GPSLatitude and GPSLongitude descriptions.
3.  Enter the Coordinates on google maps and see the location.
4. Now Get the GPSLatitudeRef and GPSLongitudeRef descriptions and adjust the coordinate values. In case a '-' sign had to be prepended to any coordinate, the location so gotten would be waaay off.

**What I expected would happen:**

I was expecting that the GPSLatitude and GPSLongitude values returned would be the final numbers but one has to also look at their Refs and add a "-" sign if Lat has "S" value or LongitudeRef has "W" value.

**What really happened:**

I just got the raw coordinates and had to handle the signs on my own. This is not a biggie but for someone who has no idea about this the results did not make any sense especially for something as easy as adding a sign to the GPSLat or Long strings.

**Comment by mattiasw** [comment]
Hi! I can definitely understand the confusion from this setup if one hasn't run into it before. However, this is what is recorded in the tag itself. What is presented when looking at it should reflect that and not transform it to something other than the Exif specification says. My guess is that you are not alone in this though. What I definitely could do is add a comment to the README on how to retrieve the full GPS information. And maybe it would be possible to somehow add an additional "fake" tag with the combined values. I will have to think about what the best solution for that would be though.

**Comment by arnav13081994** [comment]
Great! I think just adding to the Readme should be enough since the tags returned are standard and would be the same in case someone was doing this in Java or Python etc too.

With that being said, the developer in me would like to see the "fakeGPSLat" tag too!

I think your solution of creating 2 fake tags should be good. I don't know anything about how these tags are named etc but I'm guessing you could simply add something here: https://github.com/mattiasw/ExifReader/blob/master/src/tag-names-gps-ifd.js#L29

**Comment by mattiasw** [comment]
I will add it to the README, thanks for reporting the confusion. :-) Regarding fake tags I think clashing names is probably an issue to take into account. But I will think about it. Could be a useful feature for other things too.

**Comment by Satsh24** [comment]
Hey @mattiasw I came across this library while in my search of finding tools to extract colorSpace from JPG/JPEG Images. Hoping this library has that functionality, I tried to install this on React project(built using Create React App) but the installation is failing as webpack cli config is not  available. How do I fix it? Thnx!

**Comment by mattiasw** [comment]
Hi! It does indeed support the ColorSpace tag. Would be great though if you could open a new ticket with this question instead of using an old one and then add the exact error message you're getting.

**Comment by Satsh24** [comment]
Sure thanks for the quick response. Here is the [issue I created anyway](https://github.com/mattiasw/ExifReader/issues/89).

**Comment by mattiasw** [comment]
Release 3.11.0 has a new `gps` group with the requested format using minus signs.
