### ISSUE TITLE
Suggestion: Provide numerator/denominator for rational fields

### ISSUE THREAD

**Issue by jgalrito** [mattiasw/ExifReader#76]
Suggestion: Rational fields (ex: ExposureTime) should provide their raw value as a numerator/denominator pair. That would be very useful for displaying without rounding errors/loss of precision.

**Comment by mattiasw** [comment]
Hi! I can see why that would be valuable. I may not have thought this fully through yet :-), but what would you think about a "raw" value, the actual bytes for that tag? Or would that be unnecessarily crude? What I'm thinking is that the majority of users are probably satisfied with the calculated and rounded value, and a raw value would cater to anyone wanting more choice no matter which tag they are interested in, although with some extra work (in this case it's four bytes for each of numerator and denominator). Byte order would be an issue though, but I guess that could be something that would always be converted to for example big endian.

**Comment by jgalrito** [comment]
Hello!

Maybe raw was not the best name for it. For my use case a string representation "N/D" or an array [N, D] would be enough. This could even go into the "description" as the value already contains, well, the value ;)

As for to which fields this would be valuable, I'd say only ones where there is a possibility that information is lost (in this case due to rounding). From what I can see in the EXIF spec this would be RATIONAL and SRATIONAL values only.

**Comment by mattiasw** [comment]
I like the idea of putting it in the description, e.g. `1/250`. Not sure if it maybe could be seen as a breaking change though. But my guess is people are not using description in that way, especially not for rational numbers. What do you think? And what's your plan for the closed PRs? :-)

**Comment by jgalrito** [comment]
Yeah I guess putting them in the description would be a breaking change.

As for the PRs I was trying some stuff out but then realized it was breaking in the case of RATIONAL arrays (like GPSLatitude). I've fixed it now on my fork, I can open the PR again and you make with it what you will, as my solution is probably not very elegant :)

**Comment by mattiasw** [comment]
I actually know of other tags too that would be better off with another description. Maybe I shouldn't be so scared of major version updates. :-) Especially when it in reality is quite a small change. I will soon be away from my computer for several weeks (scary!) so that naturally forces me not to stress this and let it sink in. I will take this up again next year. Hope you're not in a hurry. And thanks for the PR. Depending on description update or not I may use all or part of it.

**Comment by jgalrito** [comment]
Well, as long as the changes are documented I suppose it's ok ;) I'm somewhat in a hurry but meanwhile I can use my fork. Basically I added a "raw" property to the read tag object which is undefined in all types of nodes except RATIONAL/SRATIONAL, in which it the value is represented as a `[numerator, denominator]` pair (in the case of an array, an array of these pairs).

Thank you for your work and have a nice computer vacation!

**Comment by mattiasw** [comment]
@jgalrito I made a breaking change (see #83), keeping the numerator and denominator in the `value` property of the tag to not lose any precision. Also updated some rational descriptions. I think this is how it should have been from the start. Does this seem like a suitable solution to your issue?

**Comment by jgalrito** [comment]
@mattiasw seems perfect to me!

**Comment by mattiasw** [comment]
Fixed in #83.
