### ISSUE TITLE
Are there plans to support reading exif tags from png image?

### ISSUE THREAD

**Issue by avnermosh** [mattiasw/ExifReader#81]
Are there plans to support reading exif tags from png image?
Thanks,
Avner

**Comment by mattiasw** [comment]
I have thought about it but have not had the time yet. I looked at it some years ago (see below) but at that point there was not specification for Exif in PNG images (at least not official). Now there is, and ExifReader also supports XMP which PNGs have had for a while so it is indeed a better situation now than in 2013. I believe there are a couple of other things I would want to do first though so I can't say a timeline for it.

Old duplicate ticket for reference: https://github.com/mattiasw/ExifReader/issues/11

**Comment by mattiasw** [comment]
Initial support with non-compressed XMP tags in PNGs added in 3.1.0. If you're missing some tags, open a new issue with an example image.
