### ISSUE TITLE
Suggestion: IPTC and XMP Support for TIFF images.

### ISSUE THREAD

**Issue by writecode** [mattiasw/ExifReader#92]
**Suggestion:** IPTC and XMP Support for TIFF images.
It seems EXIF only is supported with TIFF images.

**Comment by mattiasw** [comment]
Hi! Do you have one or a couple of example images that contain IPTC and XMP?

**Comment by writecode** [comment]
Here zipped two tiff images.
[Example-Tiffs.zip](https://github.com/mattiasw/ExifReader/files/4462283/Example-Tiffs.zip)

I'm specifically interested in the Keywords or Caption-Abstract:
That is also stored as dc:description dc:subject 

IPTC:
![image](https://user-images.githubusercontent.com/621322/79004262-b0afc500-7b54-11ea-93e0-325a1bfe5ebd.png)

XMP Lake1.tiff:
![image](https://user-images.githubusercontent.com/621322/79004594-56fbca80-7b55-11ea-8da6-abc276a1a6a0.png)

XMP Lake2.tiff:
![image](https://user-images.githubusercontent.com/621322/79004623-6aa73100-7b55-11ea-903f-9f6e582c0fdb.png)

**Comment by mattiasw** [comment]
Thanks, I will have a look.

**Comment by mattiasw** [comment]
Fixed in version 3.7.0. Thanks for the suggestion!

**Comment by writecode** [comment]
Thank you for your fast implementation - Works perfect!
