### ISSUE TITLE
png missing tags

### ISSUE THREAD

**Issue by mcaramb** [mattiasw/ExifReader#97]
Hmm.. running your global example, and not seeing anything but the basic tags. All I need is the ImageDescription tag. Is it just an incorrectly saved png? Compression is off, and I am embedding the metatag in photoshop CS6 which is XMP based, so it should be ok... is the image wrong or my implementation? 

Thanks... image attached.
![test1](https://user-images.githubusercontent.com/63865006/79585940-1bea2180-8096-11ea-85d6-4cb260fdcd76.png)

Image Width | 400px
-- | --
Image Height | 398px
Bit Depth | 8
Color Type | RGB
Compression | Deflate/Inflate
Filter | Adaptive
Interlace | Noninterlaced

**Comment by mattiasw** [comment]
Hi! It seems to be the image. I can't find such a tag even using exiftool (except ICC profile, but there is no image description in there). I tried both locally and online (http://exif.regex.info/exif.cgi).

**Comment by mcaramb** [comment]
Thanks but I just figured it out! It was the file. Photoshop CS6 apparently DOES NOT save tags in PNG as XMP, just EXIF. I had to use exiftool command line and specify the XMP group to get the tag to stick. ie:
![test1](https://user-images.githubusercontent.com/63865006/79592165-38d72280-809f-11ea-8d0d-574c55e347c7.png)


exiftool -XMP:ImageDescription='Hello this is a test' test1.png

New working file attached

**Comment by mcaramb** [comment]
Also, are all those script dependencies utils.js, source.js, exif-reader.js, exif.js, style.css needed to simply read one tag from an already hard coded and stored image? I'm trying to keep this as simple as possible. All my images will only be pngs and just need to pull that one Image Description tag.

I'm sorry, i don't expect you to do all my code for me, but I'm having to dig through alot of stuff here that I don't seem to need to know about and this will take time to trim down. Could you fill in the blanks for me? I'm a bit confused as to a simplified implementation. Here's a quick sample of what I'm trying to do in HTML and javascript:

ie:
<html>
<head>
<title>test</title>

// your dependencies

<script src = ' ???' />
<script src = ' ???' />

// my scripts

<script>
myimage=new Image();
myimage.src='test1.png';

function getinfo() {
   // which function do I call?
    ??? ();

   // then which variable is returned?
   var ImgDesc= ???

   alert (ImgDesc);
   }
</script>
</head>
<body onload='getinfo();'>
</body>
</html>

**Comment by mattiasw** [comment]
All those files are not needed, sorry if that isn't clear. They are just there to present the page. You only need the `exif-reader.js` (this is the actual library) and then the code that uses it in `exif.js`. However, I don't have an example for your specific case with an image element. You need to load the image data. The example page lets a user select an image from their computer. Will that work for you or do you need to use a server-side image in an image element as in your setup above?

Generally I would say getting the image data is the part which is going to be different for each use case. A part from that, using the library should not be any trickier than the few lines shown in the README.
```
const tags = ExifReader.load(fileBuffer);
const imageDate = tags['ImageDescription'].description;
```

**Comment by mcaramb** [comment]
Yes, I need to pull the file buffer from a stored image on the server side, not though the client browse. would that look like (from my previous example) const tags = ExifReader.load(myimage); ?

**Comment by mattiasw** [comment]
Yeah, you have to get the actual bytes from the image which unfortunately is going to be trickier than that. The browser only keeps a pixel representation of that image, not the rest of the image data. You can instead load it using either `XMLHttpRequest` or `fetch`. The next problem with that is that the server with the image will have to pass the correct CORS headers, but if that is your own server it should be possible.

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

**Comment by mattiasw** [comment]
Here is an example using `fetch`. Make sure you have `<script src="path/to/exif-reader.js"></script>` on your page and then run this:
```
fetch('https://i.imgur.com/DX2kvpG.jpg')
  .then(response => response.arrayBuffer())
  .then(data => console.log(window.ExifReader.load(data)));
```

**Comment by mcaramb** [comment]
Oh man, thank you!
<img width="313" alt="Screen Shot 2020-04-17 at 12 01 11 PM" src="https://user-images.githubusercontent.com/63865006/79603234-8ceb0280-80b1-11ea-8b32-c3d66be3d1a8.png">
 that works great! However, PNG doesn't seem to work. It works fine for JPG, but I get image format not supported when I point it to a PNG

**Comment by mcaramb** [comment]
Oh man thank you! That works great, but only for jpgs. When I point it to a png file I get 'invalid image format' 
<img width="663" alt="Screen Shot 2020-04-17 at 1 43 10 PM" src="https://user-images.githubusercontent.com/63865006/79603347-cde31700-80b1-11ea-9c79-9e2153a4047c.png">

**Comment by mcaramb** [comment]
Also working fine with tiff files... tried resaving the file again, but it still doesn't recognize the png... its like the header information isn't being sent correctly. Is it a webpack issue? its coming from the image-header.js

**Comment by mattiasw** [comment]
It works with PNGs for me, for example with this one: https://i.imgur.com/y3sGF.png

**Comment by mattiasw** [comment]
OK, so now I got that error you got. It happens when the file is not found. :-) I guess it tries to read the 404 page the server responds with, which of course is not an image. Not sure this is the problem you're having, but just to make sure, can you check the Network tab in the devtools and see what the server responds with for the image URL?

**Comment by mcaramb** [comment]
naw, that's not my problem apparently.. the url is correct and it's loading:  http://www.retroresource.com/test2.png

**Comment by mcaramb** [comment]
more confusion... the constants variable is set correctly in webpack;s constants.js file
<img width="658" alt="Screen Shot 2020-04-17 at 2 33 33 PM" src="https://user-images.githubusercontent.com/63865006/79607204-7bf1bf80-80b8-11ea-9780-95fe1ec2de4c.png">

**Comment by mcaramb** [comment]
oh wait those are just the initial defaults.... so now not sure which of these two events aren't firing properly atm... 
<img width="740" alt="Screen Shot 2020-04-17 at 2 38 39 PM" src="https://user-images.githubusercontent.com/63865006/79607631-2538b580-80b9-11ea-972e-cf416a155893.png">

**Comment by mattiasw** [comment]
Unless you made a custom build those constants should not matter. When I put that exact image on my server it works.

**Comment by mcaramb** [comment]
ok then... sorry, wrong file... but I'm thinking it may be just this client computer's implementation of webpack. It a mac, catalina, with firefox. May try it on another pc/browser or try using XMLHttpRequest instead. Just weirdness. thanks for the help!

**Comment by mattiasw** [comment]
Agree, it's weird, especially when other images work, so it may be some local thing I guess. Hope you solve it, and if you have any other issues, feel free to ask again.
