### ISSUE TITLE
Reports "right-top" for portrait photos

### ISSUE THREAD

**Issue by derwaldgeist** [mattiasw/ExifReader#99]
I am facing a very strange phenomenon in a mobile app that has been out there for a while.

This app uses a web view (on both iOS and Android) to capture photos via the device camera (this is triggered by a file input), then loads the buffer into a canvas, for preview, before uploading the photo to the server.

Before I load the image into the canvas via `blueimp-load-image`, I process it via `exifreader` to get the orientation. This orientation is then handed over to `blueimp-load-image`.

This setup worked perfectly for several months now.

All of the sudden (i.e. without any changes), I first noticed on iOS devices that images that had been taken in portrait mode were rotated to the right. I debugged this and saw that `exifreader` reported `right-top` for the image. I assumed a bug in the most recent iOS version and workarounded this by setting the portrait orientation on these devices. Then, all of a sudden, my Android devices started to show the same behaviour (i.e. all except a Samsung S10, to be precise). Also here, the EXIF data now shows `right-top` for photos that had been shot when the camera device camera was upright.

I checked it with older versions of my app and newer versions, all of them show this behaviour. So I can only assume that on both systems, the web view behaves differently now. Any idea what might cause this? I updated both `blueimp-load-image` as `exifreader` to the latest versions, but still the problem occurs.

If I just ignore the EXIF data and hard-set the camera orientation to portrait, the problem is gone, even I rotate the camera when taking a photo. This was not the case about 6 months ago, which was the reason why I included your library to care for camera rotation.

**Comment by mattiasw** [comment]
Hi! I agree that it's really strange that the behavior changed suddenly. However, `right-top` actually sounds correct for a portrait photo. I'm just guessing here, but could it be possible that somehow the handling of orientation was wrong before and now the implementation over-compensates or something?

**Comment by derwaldgeist** [comment]
> However, `right-top` actually sounds correct for a portrait photo.

Are you sure? According to this website, `right-top` (= 6) is an image that is rotated to the right:
https://www.impulseadventure.com/photo/exif-orientation.html

To my understanding, portrait would be `top-left`(= 1).

The app itself is locked into portrait. Maybe that's the reason, so all images seem to be rotated relative to the page orientation? Strange thing is that this was definitely not the case a couple of months before.

**Comment by derwaldgeist** [comment]
I double-checked this in the mobile Safari browser. If its running in portrait mode (= normal website viewing on smartphones) and I take a picture this way, the picture is reported as "right-top".

But the image that I get from the file buffer is actually upright. In fact, it is always upright, no matter how the camera was rotated when the picture has been taken.

This behaviour definitely differs from that a couple of months ago. Strange thing is, it happens on both iOS and Android.

Fun thing is: The only exception is if you 
a) pick an image from your photo library on iOS AND
b) reduce the image size before handing it over to the web app
In this case, a portrait image actually appears to be upside down. If you don't reduce the image size manually, an image selected from the photo library is always upright.

**Comment by mattiasw** [comment]
Pretty sure. On that page, the right-most image, 6 (`right-top`), has the camera outline in portrait orientation. Also the Screen View row shows the view as portrait. And the table describing row #0 and column #0 seems to match portrait to the value 6.

It's hard to say what the issue could be. It does sound weird. I saw that `blueimp-load-image` has some build-in Exif orientation handling if you activate it. I wouldn't want to lose you :-), but you can't use that instead of ExifReader? Since it will also just read the image meta data it will most probably have the same issue though, but then there would be one less piece to keep track of at least.

**Comment by derwaldgeist** [comment]
The more I think about it, I don't think it's a problem in the EXIF library. It seems to be an inconsistency in how mobile browsers handle image uploads. They deliver upright images (now), but they report the EXIF data of the original camera shot (which may not be upright). And this was definitely not the case a couple of months ago. Otherwise, I wouldn't have needed an EXIF parser at all.

(Yes, I saw that the blueimp library has EXIF support, but it won't explain how you can use it in combination with the ES6 module library version. I didn't manage to set this up correctly, so I looked for a separate library, yours :-)

**Comment by mattiasw** [comment]
Hope you sort it out. If I can help with anything else I'll be glad to help.

**Comment by derwaldgeist** [comment]
An update on this: After I removed the EXIF correction (because I thought it was done by the Webviews automatically now), I got reports from folks using iPhone XR and 11 that this caused their photos to be wrongly rotated again. Hence, it seems to depend on the actual device / camera. On my iPhone X and all my Android devices, it works without manual correction, on Samsung S10 and iPhone XR/11 it does not work, even when using the very same version of Android / iOS. Unfortunately, there is no way to tell which devices behaves how. It's really annoying.

**Comment by mattiasw** [comment]
I can really see how annoying that is... Is there anything I can test for you? I have an older LG with Android 9.

**Comment by derwaldgeist** [comment]
Thanks for the offer, that would be super helpful. To test it, just go to marblear.com, download our app, place a "Marble" by following the tutorial, open it and take a picture. If it shows up upright, everything is fine.

BTW: I found out that the problems with the iPhone XR and iPhone 11 were related to the person using iOS 13.3. After upgrading to iOS 13.4, the orientation was auto-compensated, like on my iPhone X which already was on iOS 13.4. Hence, I can confirm that the different behavior of the WkWebView depends on the iOS version. But on Android, I still have no idea how to detect the behavior, as even with the same Android version the results may differ.

**Comment by mattiasw** [comment]
That worked fine, photo is upright. Using an LG V30, Android 9 (can't find anything more specific than that).

**Comment by mattiasw** [comment]
While I was working on my own web app I was hit by this too! Not using webviews in a mobile app though, but I'm thinking the cause could be the same. Apparently Firefox, Chrome and Safari are all looking at automatically rotating images according to their orientation meta tag. Firefox and Chrome has already shipped this in the latest releases. Not sure when it's due in Safari. I noticed it when I got different results in Firefox and Chrome and then discovering I had a quite old version of Chrome installed. Now they both auto-rotate. Maybe this is something you could look into in your case too.

References:
https://www.fxsitecompat.dev/en-CA/docs/2020/jpeg-images-are-now-rotated-by-default-according-to-exif-data/
https://bugs.webkit.org/show_bug.cgi?id=89052

**Comment by derwaldgeist** [comment]
Thanks for the feedback on the LG and the additional infos. It seems as if Apple has included the auto-rotation in iOS 13.4, but iOS 13.3 still does not do it. So I had to include a iOS version detection to react accordingly. I found no other way to tell if the devices actually auto-rotate or not.

**Comment by mattiasw** [comment]
Could you try this maybe? According to the links above this is the property they changed default value for.
```
var styles = getComputedStyle(document.querySelector('#some-image'));
if (styles.getPropertyValue('image-orientation') === 'from-image') {
    // Images are auto-rotated.
}
```

**Comment by derwaldgeist** [comment]
Thanks for the info. Yeah, I am currently reading through these bugs, they are very informative. Seems as Slack has been hit by this change, too: https://bugzilla.mozilla.org/show_bug.cgi?id=1634180

**Comment by mattiasw** [comment]
That's an interesting thread. And this comment explains why setting `image-orientation: from-image;` myself didn't have any effect in Chrome: "[...] Chromium/Blink apparently didn't support image-orientation at all until now."

**Comment by derwaldgeist** [comment]
On macOS Catalina, it works (and also your test). But only if I add an actual image to the DOM. If I just create it using `document.createElement()`, it won't have any computed styles yet.

**Comment by asokani** [comment]
@derwaldgeist you can use this hack: https://github.com/blueimp/JavaScript-Load-Image/blob/af40950cd629651a249a6639033fe28c6b968ac7/js/load-image-orientation.js#L87

**Comment by OliverJAsh** [comment]
If you want to detect Exif orientation in iOS Safari 12 and below, the image must also be appended to the DOM: https://stackblitz.com/edit/feature-detect-img-orientation?file=index.ts

**Comment by LuisBonsembiante** [comment]
@derwaldgeist Hi, I have the same issue in my react.native app, did you find any solution?..regards.
